; GENERATED by treebank-sdf3 from the scope/binds/refers attributes of
; hcl.sdf3, in treebank's locals vocabulary. bindings.json is the exact
; data; this is the query-dialect view of it.

; --- where names live
[(config_file) (body) (body) (for_tuple_expr) (for_object_expr) (template_for) (template_for)] @local.scope

; --- what introduces a name
(attribute name: (_name) @local.definition.attribute)

(block type: (_name) @local.definition.block)

; --- what mentions a name
(identifier) @local.reference
