/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 2
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 3

enum ts_symbol_identifiers {
  sym_id = 1,
  anon_sym_SEMI = 2,
  anon_sym_EQ = 3,
  sym_int_type = 4,
  sym_char_type = 5,
  anon_sym_LT = 6,
  anon_sym_COMMA = 7,
  anon_sym_GT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_GT_GT = 11,
  anon_sym_PLUS = 12,
  sym_comment = 13,
  sym_num = 14,
  sym_program = 15,
  sym_decl = 16,
  sym_assign = 17,
  sym_expr_stmt = 18,
  sym__stmt = 19,
  sym_template_id = 20,
  sym__type = 21,
  sym_exp_num = 22,
  sym_call = 23,
  sym_shr = 24,
  sym_add = 25,
  sym_lt = 26,
  sym_gt = 27,
  sym__exp = 28,
  aux_sym_program_repeat1 = 29,
  aux_sym_template_id_repeat1 = 30,
  aux_sym_call_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_id] = "id",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [sym_int_type] = "int_type",
  [sym_char_type] = "char_type",
  [anon_sym_LT] = "<",
  [anon_sym_COMMA] = ",",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_PLUS] = "+",
  [sym_comment] = "comment",
  [sym_num] = "num",
  [sym_program] = "program",
  [sym_decl] = "decl",
  [sym_assign] = "assign",
  [sym_expr_stmt] = "expr_stmt",
  [sym__stmt] = "_stmt",
  [sym_template_id] = "template_id",
  [sym__type] = "_type",
  [sym_exp_num] = "exp_num",
  [sym_call] = "call",
  [sym_shr] = "shr",
  [sym_add] = "add",
  [sym_lt] = "lt",
  [sym_gt] = "gt",
  [sym__exp] = "_exp",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_template_id_repeat1] = "template_id_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_id] = sym_id,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_int_type] = sym_int_type,
  [sym_char_type] = sym_char_type,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_comment] = sym_comment,
  [sym_num] = sym_num,
  [sym_program] = sym_program,
  [sym_decl] = sym_decl,
  [sym_assign] = sym_assign,
  [sym_expr_stmt] = sym_expr_stmt,
  [sym__stmt] = sym__stmt,
  [sym_template_id] = sym_template_id,
  [sym__type] = sym__type,
  [sym_exp_num] = sym_exp_num,
  [sym_call] = sym_call,
  [sym_shr] = sym_shr,
  [sym_add] = sym_add,
  [sym_lt] = sym_lt,
  [sym_gt] = sym_gt,
  [sym__exp] = sym__exp,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_template_id_repeat1] = aux_sym_template_id_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_int_type] = {
    .visible = true,
    .named = true,
  },
  [sym_char_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_template_id] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_exp_num] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_shr] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_template_id_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_function = 2,
  field_left = 3,
  field_name = 4,
  field_right = 5,
  field_target = 6,
  field_type = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_right] = "right",
  [field_target] = "target",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 0},
  [1] =
    {field_name, 1},
    {field_type, 0},
  [3] =
    {field_left, 0},
    {field_right, 2},
  [5] =
    {field_target, 0},
    {field_value, 2},
  [7] =
    {field_arguments, 2},
    {field_name, 0},
  [9] =
    {field_arguments, 2},
    {field_function, 0},
  [11] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_name, 0},
  [14] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__exp,
  sym__stmt,
  sym__type,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__exp] = {.index = 0, .length = 7},
  [sym__stmt] = {.index = 7, .length = 3},
  [sym__type] = {.index = 10, .length = 4},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_add,
    sym_call,
    sym_exp_num,
    sym_gt,
    sym_id,
    sym_lt,
    sym_shr,
  [7] =
    sym_assign,
    sym_decl,
    sym_expr_stmt,
  [10] =
    sym_char_type,
    sym_id,
    sym_int_type,
    sym_template_id,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '(', 10,
        ')', 11,
        '+', 13,
        ',', 7,
        '/', 2,
        ';', 4,
        '<', 6,
        '=', 5,
        '>', 9,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '>') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(12);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_num);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'h') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_int_type);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_char_type);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0, .reserved_word_set_id = 1},
  [2] = {.lex_state = 0, .reserved_word_set_id = 1},
  [3] = {.lex_state = 0, .reserved_word_set_id = 1},
  [4] = {.lex_state = 0, .reserved_word_set_id = 1},
  [5] = {.lex_state = 0, .reserved_word_set_id = 1},
  [6] = {.lex_state = 0, .reserved_word_set_id = 1},
  [7] = {.lex_state = 0, .reserved_word_set_id = 1},
  [8] = {.lex_state = 0, .reserved_word_set_id = 1},
  [9] = {.lex_state = 0, .reserved_word_set_id = 1},
  [10] = {.lex_state = 0, .reserved_word_set_id = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0, .reserved_word_set_id = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0, .reserved_word_set_id = 1},
  [27] = {.lex_state = 0, .reserved_word_set_id = 1},
  [28] = {.lex_state = 0, .reserved_word_set_id = 1},
  [29] = {.lex_state = 0, .reserved_word_set_id = 1},
  [30] = {.lex_state = 0, .reserved_word_set_id = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1, .reserved_word_set_id = 1},
  [34] = {.lex_state = 1, .reserved_word_set_id = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1, .reserved_word_set_id = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0, .reserved_word_set_id = 1},
};

static const TSSymbol ts_reserved_words[2][MAX_RESERVED_WORD_SET_SIZE] = {
  [1] = {
    sym_int_type,
    sym_char_type,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_int_type] = ACTIONS(1),
    [sym_char_type] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_num] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(43),
    [sym_decl] = STATE(27),
    [sym_assign] = STATE(27),
    [sym_expr_stmt] = STATE(27),
    [sym__stmt] = STATE(3),
    [sym_template_id] = STATE(39),
    [sym__type] = STATE(44),
    [sym_exp_num] = STATE(14),
    [sym_call] = STATE(14),
    [sym_shr] = STATE(14),
    [sym_add] = STATE(14),
    [sym_lt] = STATE(14),
    [sym_gt] = STATE(14),
    [sym__exp] = STATE(25),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_id] = ACTIONS(7),
    [sym_int_type] = ACTIONS(9),
    [sym_char_type] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_num] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_decl] = STATE(27),
    [sym_assign] = STATE(27),
    [sym_expr_stmt] = STATE(27),
    [sym__stmt] = STATE(2),
    [sym_template_id] = STATE(39),
    [sym__type] = STATE(44),
    [sym_exp_num] = STATE(14),
    [sym_call] = STATE(14),
    [sym_shr] = STATE(14),
    [sym_add] = STATE(14),
    [sym_lt] = STATE(14),
    [sym_gt] = STATE(14),
    [sym__exp] = STATE(25),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_id] = ACTIONS(15),
    [sym_int_type] = ACTIONS(18),
    [sym_char_type] = ACTIONS(18),
    [sym_comment] = ACTIONS(3),
    [sym_num] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym_decl] = STATE(27),
    [sym_assign] = STATE(27),
    [sym_expr_stmt] = STATE(27),
    [sym__stmt] = STATE(2),
    [sym_template_id] = STATE(39),
    [sym__type] = STATE(44),
    [sym_exp_num] = STATE(14),
    [sym_call] = STATE(14),
    [sym_shr] = STATE(14),
    [sym_add] = STATE(14),
    [sym_lt] = STATE(14),
    [sym_gt] = STATE(14),
    [sym__exp] = STATE(25),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(24),
    [sym_id] = ACTIONS(7),
    [sym_int_type] = ACTIONS(9),
    [sym_char_type] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_num] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_num,
    ACTIONS(26), 1,
      sym_id,
    ACTIONS(28), 1,
      anon_sym_RPAREN,
    STATE(15), 1,
      sym__exp,
    STATE(14), 6,
      sym_exp_num,
      sym_call,
      sym_shr,
      sym_add,
      sym_lt,
      sym_gt,
  [24] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_num,
    ACTIONS(26), 1,
      sym_id,
    STATE(18), 1,
      sym__exp,
    STATE(14), 6,
      sym_exp_num,
      sym_call,
      sym_shr,
      sym_add,
      sym_lt,
      sym_gt,
  [45] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_num,
    ACTIONS(26), 1,
      sym_id,
    STATE(17), 1,
      sym__exp,
    STATE(14), 6,
      sym_exp_num,
      sym_call,
      sym_shr,
      sym_add,
      sym_lt,
      sym_gt,
  [66] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_num,
    ACTIONS(26), 1,
      sym_id,
    STATE(16), 1,
      sym__exp,
    STATE(14), 6,
      sym_exp_num,
      sym_call,
      sym_shr,
      sym_add,
      sym_lt,
      sym_gt,
  [87] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_num,
    ACTIONS(26), 1,
      sym_id,
    STATE(31), 1,
      sym__exp,
    STATE(14), 6,
      sym_exp_num,
      sym_call,
      sym_shr,
      sym_add,
      sym_lt,
      sym_gt,
  [108] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_num,
    ACTIONS(26), 1,
      sym_id,
    STATE(19), 1,
      sym__exp,
    STATE(14), 6,
      sym_exp_num,
      sym_call,
      sym_shr,
      sym_add,
      sym_lt,
      sym_gt,
  [129] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_num,
    ACTIONS(26), 1,
      sym_id,
    STATE(23), 1,
      sym__exp,
    STATE(14), 6,
      sym_exp_num,
      sym_call,
      sym_shr,
      sym_add,
      sym_lt,
      sym_gt,
  [150] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      anon_sym_GT,
    ACTIONS(34), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 6,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
      anon_sym_PLUS,
  [168] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      anon_sym_GT,
    ACTIONS(34), 1,
      anon_sym_LPAREN,
    ACTIONS(36), 1,
      sym_id,
    ACTIONS(38), 1,
      anon_sym_EQ,
    ACTIONS(40), 1,
      anon_sym_LT,
    ACTIONS(30), 3,
      anon_sym_SEMI,
      anon_sym_GT_GT,
      anon_sym_PLUS,
  [192] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_GT,
    ACTIONS(43), 6,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
      anon_sym_PLUS,
  [207] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      anon_sym_GT,
    ACTIONS(30), 6,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
      anon_sym_PLUS,
  [222] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    ACTIONS(51), 1,
      anon_sym_GT,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 1,
      anon_sym_GT_GT,
    ACTIONS(57), 1,
      anon_sym_PLUS,
    STATE(32), 1,
      aux_sym_call_repeat1,
  [247] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_GT,
    ACTIONS(59), 6,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
      anon_sym_PLUS,
  [262] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_GT_GT,
    ACTIONS(57), 1,
      anon_sym_PLUS,
    ACTIONS(65), 1,
      anon_sym_GT,
    ACTIONS(63), 4,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [281] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_GT_GT,
    ACTIONS(57), 1,
      anon_sym_PLUS,
    ACTIONS(69), 1,
      anon_sym_GT,
    ACTIONS(67), 4,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [300] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_PLUS,
    ACTIONS(73), 1,
      anon_sym_GT,
    ACTIONS(71), 5,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
  [317] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_GT,
    ACTIONS(75), 6,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
      anon_sym_PLUS,
  [332] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_GT,
    ACTIONS(79), 6,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
      anon_sym_PLUS,
  [347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_GT,
    ACTIONS(83), 6,
      anon_sym_SEMI,
      anon_sym_LT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT_GT,
      anon_sym_PLUS,
  [362] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      anon_sym_GT,
    ACTIONS(55), 1,
      anon_sym_GT_GT,
    ACTIONS(57), 1,
      anon_sym_PLUS,
    ACTIONS(87), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [382] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_id,
    STATE(38), 1,
      sym__type,
    STATE(39), 1,
      sym_template_id,
    ACTIONS(9), 2,
      sym_int_type,
      sym_char_type,
  [399] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      anon_sym_GT,
    ACTIONS(55), 1,
      anon_sym_GT_GT,
    ACTIONS(57), 1,
      anon_sym_PLUS,
    ACTIONS(91), 1,
      anon_sym_SEMI,
  [418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym_num,
    ACTIONS(95), 3,
      sym_int_type,
      sym_char_type,
      sym_id,
  [431] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_num,
    ACTIONS(99), 3,
      sym_int_type,
      sym_char_type,
      sym_id,
  [444] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_id,
    STATE(39), 1,
      sym_template_id,
    STATE(41), 1,
      sym__type,
    ACTIONS(9), 2,
      sym_int_type,
      sym_char_type,
  [461] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_num,
    ACTIONS(103), 3,
      sym_int_type,
      sym_char_type,
      sym_id,
  [474] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_num,
    ACTIONS(107), 3,
      sym_int_type,
      sym_char_type,
      sym_id,
  [487] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      anon_sym_GT,
    ACTIONS(55), 1,
      anon_sym_GT_GT,
    ACTIONS(57), 1,
      anon_sym_PLUS,
    ACTIONS(109), 1,
      anon_sym_SEMI,
  [506] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_call_repeat1,
  [519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 3,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_id,
  [528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_id,
  [537] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    ACTIONS(119), 1,
      anon_sym_GT,
    STATE(36), 1,
      aux_sym_template_id_repeat1,
  [550] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_GT,
    STATE(36), 1,
      aux_sym_template_id_repeat1,
  [563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(36), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [574] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_GT,
    STATE(35), 1,
      aux_sym_template_id_repeat1,
  [587] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 3,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_id,
  [596] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    ACTIONS(130), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_call_repeat1,
  [609] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [617] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_SEMI,
  [624] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
  [631] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_id,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 24,
  [SMALL_STATE(6)] = 45,
  [SMALL_STATE(7)] = 66,
  [SMALL_STATE(8)] = 87,
  [SMALL_STATE(9)] = 108,
  [SMALL_STATE(10)] = 129,
  [SMALL_STATE(11)] = 150,
  [SMALL_STATE(12)] = 168,
  [SMALL_STATE(13)] = 192,
  [SMALL_STATE(14)] = 207,
  [SMALL_STATE(15)] = 222,
  [SMALL_STATE(16)] = 247,
  [SMALL_STATE(17)] = 262,
  [SMALL_STATE(18)] = 281,
  [SMALL_STATE(19)] = 300,
  [SMALL_STATE(20)] = 317,
  [SMALL_STATE(21)] = 332,
  [SMALL_STATE(22)] = 347,
  [SMALL_STATE(23)] = 362,
  [SMALL_STATE(24)] = 382,
  [SMALL_STATE(25)] = 399,
  [SMALL_STATE(26)] = 418,
  [SMALL_STATE(27)] = 431,
  [SMALL_STATE(28)] = 444,
  [SMALL_STATE(29)] = 461,
  [SMALL_STATE(30)] = 474,
  [SMALL_STATE(31)] = 487,
  [SMALL_STATE(32)] = 506,
  [SMALL_STATE(33)] = 519,
  [SMALL_STATE(34)] = 528,
  [SMALL_STATE(35)] = 537,
  [SMALL_STATE(36)] = 550,
  [SMALL_STATE(37)] = 563,
  [SMALL_STATE(38)] = 574,
  [SMALL_STATE(39)] = 587,
  [SMALL_STATE(40)] = 596,
  [SMALL_STATE(41)] = 609,
  [SMALL_STATE(42)] = 617,
  [SMALL_STATE(43)] = 624,
  [SMALL_STATE(44)] = 631,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__exp, 1, 0, 0), SHIFT(24),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp_num, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exp_num, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 3),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add, 3, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lt, 3, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lt, 3, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_gt, 3, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_gt, 3, 0, 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shr, 3, 0, 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shr, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 6),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 6),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 8),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 5, 0, 8),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_stmt, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr_stmt, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stmt, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 4, 0, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assign, 4, 0, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 3, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decl, 3, 0, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_id, 5, 1, 7),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_id, 4, 1, 5),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_id_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_id_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [135] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cppish(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_id,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cppish",
    .reserved_words = &ts_reserved_words[0][0],
    .max_reserved_word_set_size = 2,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
