#!/usr/bin/env python3
"""Do the three lowerings confer? One table per spike.

    python3 tools/confer.py spike/mini [spike/rubyish ...]

For every case of `<dir>/test/corpus/*.txt` the tree-sitter parser's verdict
is the corpus expectation itself (that spike's verify.sh holds it there
with `tree-sitter test`); the ANTLR and winnow verdicts are read from
`antlr-results.md` and `winnow-results.md`, which antlr_check.py and
winnow_check.py write in one format. Writes `<dir>/confer-results.md`:
a row per case with the three verdicts and what the row means --

  agree     all three give the corpus tree
  source    tree-sitter widened past the source and another backend
            rejects the input, which is what the SDF3 says
  differ    a backend gives another tree or rejects: a capability
            difference the results file names, or a bug

and exits non-zero only when a `differ` row's backend is winnow, since the
ANTLR differences are the measured capability gaps of notes/metagrammar.md
§16 and this tool is not the place to re-adjudicate them.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from antlr_check import read_corpus  # noqa: E402


def verdicts(path: Path):
    """case name -> (verdict, got)."""
    if not path.exists():
        return None
    out = {}
    cur = None
    got = []
    in_got = False
    for line in path.read_text().splitlines():
        m = re.match(r"^## (PASS|FAIL|SOURCE): (.*)$", line)
        if m:
            if cur:
                out[cur[1]] = (cur[0], "\n".join(got).strip())
            cur = (m.group(1), m.group(2))
            got = []
            in_got = False
            continue
        if line == "got:":
            in_got = True
            continue
        if in_got and line.startswith("```"):
            in_got = "open" if in_got is True else False
            continue
        if in_got == "open":
            got.append(line)
    if cur:
        out[cur[1]] = (cur[0], "\n".join(got).strip())
    return out


def main(spikes):
    bad = 0
    for spike in spikes:
        spike = Path(spike).resolve()
        cases = read_corpus(next((spike / "test" / "corpus").glob("*.txt")))
        antlr = verdicts(spike / "antlr-results.md")
        winnow = verdicts(spike / "winnow-results.md")
        rows = []
        counts = {"agree": 0, "source": 0, "differ": 0}
        for c in cases:
            a = antlr.get(c["name"], ("n/a", "")) if antlr else ("n/a", "")
            w = winnow.get(c["name"], ("n/a", "")) if winnow else ("n/a", "")
            # antlr_check.py has no SOURCE verdict; a rejection on a case
            # tree-sitter widened is the same answer, and read as one here.
            widening = c["name"].upper().startswith("WIDENING")
            if widening and a[0] == "FAIL" and not a[1].lstrip().startswith("("):
                a = ("SOURCE", a[1])
            vs = [v for v in (a[0], w[0]) if v != "n/a"]
            if all(v == "PASS" for v in vs):
                meaning = "agree"
            elif all(v in ("PASS", "SOURCE") for v in vs):
                meaning = "source"
            else:
                meaning = "differ"
                if w[0] == "FAIL":
                    bad += 1
            counts[meaning] += 1
            rows.append((c, a, w, meaning))
        mark = {"PASS": "✓", "FAIL": "✗", "SOURCE": "✓ (rejects, as the source)", "n/a": "—"}
        out = [f"# {spike.name}: do the three lowerings confer?", ""]
        out.append("GENERATED by tools/confer.py from the corpus, antlr-results.md and winnow-results.md. tree-sitter's column is the corpus expectation, held by `tree-sitter test`.")
        out.append("")
        out.append(f"{len(cases)} cases: {counts['agree']} agree, {counts['source']} where tree-sitter widened past the source and a backend rejects as the source does, {counts['differ']} where a backend differs.")
        out.append("")
        out.append("| case | tree-sitter | ANTLR | winnow | |")
        out.append("|---|---|---|---|---|")
        for c, a, w, meaning in rows:
            name = c["name"].replace("|", "\\|")
            ts = "✓ (rejects)" if c["error"] else "✓"
            out.append(f"| {name} | {ts} | {mark[a[0]]} | {mark[w[0]]} | {meaning} |")
        differs = [(c, a, w) for c, a, w, m in rows if m == "differ"]
        if differs:
            out.append("")
            out.append("## Where they differ")
            out.append("")
            for c, a, w in differs:
                out.append(f"### {c['name']}")
                out.append("")
                out.append("```")
                out.append("expected (tree-sitter): " + (c["expected"] if not c["error"] else "(a syntax error)"))
                if a[0] == "FAIL":
                    out.append("ANTLR:                  " + a[1].replace("\n", " "))
                if w[0] == "FAIL":
                    out.append("winnow:                 " + w[1].replace("\n", " "))
                out.append("```")
                out.append("")
        (spike / "confer-results.md").write_text("\n".join(out) + "\n")
        print(f"{spike.name}: {counts['agree']} agree, {counts['source']} source, {counts['differ']} differ -> {spike / 'confer-results.md'}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
