; GENERATED by `treebank queries` from queries/highlights.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; typescript's own node types. Edit queries/highlights.scm and regenerate, or the next
; --check will fail.
;
; Omitted: typescript has _clause, but no member of it takes
; the field the pattern asks for.

; --- the leaves a reader looks at first -----------------------------------

[(comment)] @comment

; `_literal` BEFORE `_string`, and the order is the whole of it: the last
; matching pattern wins, and the two terms overlap wherever a language has a
; string literal that is also fully determined by its own text. In YAML they
; overlap completely — `_literal` is every scalar and `_string` is the three
; that are always strings — so with `_literal` last, `"quoted"` matched both
; and rendered as a NUMBER. Every quoted scalar in the language did.
(_literal) @number
[(string) (template_string)] @string

; --- the key of a pair ------------------------------------------------------
;
; A mapping key is not a value and should not be coloured like one. There is
; no vocabulary TERM for a key — `_clause` is the subordinate piece and the
; key is a field on it — so this reaches it through the field, which is also
; what makes it self-limiting: expansion drops the members that have no
; `key`, so a language whose clauses are `elif` and `case` contributes
; nothing here and only the mapping-shaped ones do.

; --- names ----------------------------------------------------------------
;
; `_identifier` is every name-shaped token, so it is the fallback that later
; patterns narrow.

[(identifier) (nested_identifier) (private_name) (type_identifier)] @variable

; --- types ------------------------------------------------------------------
;
; After `_identifier`, so a name in type position is coloured as a type
; rather than as the variable the broader pattern already claimed. Guarded
; because python declares no `_type` — its annotations are ordinary
; expressions — and YAML is what made the omission visible: a tag is the one
; piece of YAML syntax that says what a node IS, and nothing coloured it.

(_type) @type

; --- things that are called ------------------------------------------------
;
; Guarded, because not every language treebank parses computes. YAML has no
; callable and no invocation, and a pattern naming a term its grammar does
; not declare is a QueryError at load time rather than a zero-match, so the
; block is dropped for the grammars that lack the term instead of the file
; failing to compile for them.

[(function_definition) (arrow_function) (function_expression)] @function

(_invocation) @function.call

; --- control flow ----------------------------------------------------------
;
; These capture the whole construct rather than its keyword: the keyword is
; an anonymous token, and an anonymous token has no vocabulary term. A
; per-grammar supplement is where `if` and `while` themselves get coloured.
;
; Guarded for the same reason as the block above: a data language alters no
; sequential execution because it has none.

(_loop) @keyword.repeat

(_branch) @keyword.conditional

(_jump) @keyword.return

; And guarded once more, for a language that computes but never reaches
; outside its own file: HCL's `module` block is a block, and what its
; `source` means is the calling application's business rather than the
; syntax's.
(_directive) @keyword.import
