; GENERATED by `treebank queries` from queries/locals.scm -- do not edit.
;
; The source names vocabulary terms; the nominal ones below have been
; expanded into typescript's own node types. Edit queries/locals.scm and
; regenerate, or the next --check will fail.

; --- where names live ------------------------------------------------------
;
; A scope is anything that can contain a binding without leaking it. What
; counts differs per language -- a block, a function body, a module, a `do`
; end -- and each grammar declares its own members.

[(program) (function_definition) (arrow_function) (function_expression) (class_definition) (block) (static_block) (namespace_definition) (catch_clause)] @local.scope

; --- what introduces a name ------------------------------------------------
;
; The capture goes on the NAME, not on the construct: an editor renames the
; identifier, and needs the range of the thing it would rewrite. Members that
; have no `name` field are dropped when this is expanded, which is why a
; language whose bindings are positional loses those patterns rather than
; producing a pattern that cannot match.

[(function_definition name: (_) @local.definition.function) (function_expression name: (_) @local.definition.function)]

[(function_definition name: (_) @local.definition.var) (class_definition name: (_) @local.definition.var) (interface_definition name: (_) @local.definition.var) (type_alias name: (_) @local.definition.var) (enum_definition name: (_) @local.definition.var) (namespace_definition name: (_) @local.definition.var) (import_alias name: (_) @local.definition.var) (variable_declarator name: (_) @local.definition.var) (import_specifier name: (_) @local.definition.var) (field_definition name: (_) @local.definition.var) (enum_member name: (_) @local.definition.var) (type_parameter name: (_) @local.definition.var) (function_expression name: (_) @local.definition.var) (shorthand_property_pattern name: (_) @local.definition.var)]

; A parameter is a definition, and the one place a caller's name meets the
; callee's. bash has no term for it: a bash function takes `$1`, not a named
; parameter, so this is omitted there rather than dropped from everyone.
(_parameter name: (_) @local.definition.parameter)

; --- what mentions a name --------------------------------------------------
;
; Every name-shaped token is a reference until something more specific claims
; it. The locals engine resolves each against the definitions in scope, so
; over-capturing here is cheap and under-capturing is not.

[(identifier) (nested_identifier) (private_name) (type_identifier)] @local.reference
