; GENERATED by `treebank queries` from queries/locals.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; c's own node types. Edit queries/locals.scm and regenerate, or the next
; --check will fail.
;
; Omitted: c has _parameter, but no member of it takes
; the field the pattern asks for.

; --- where names live ------------------------------------------------------
;
; A scope is anything that can contain a binding without leaking it. What
; counts differs per language -- a block, a function body, a module, a `do`
; end -- and each grammar declares its own members.

[(compound_statement) (for_statement) (function_definition) (translation_unit)] @local.scope

; --- what introduces a name ------------------------------------------------
;
; The capture goes on the NAME, not on the construct: an editor renames the
; identifier, and needs the range of the thing it would rewrite. Members that
; have no `name` field are dropped when this is expanded, which is why a
; language whose bindings are positional loses those patterns rather than
; producing a pattern that cannot match.

[(preproc_function_def name: (_) @local.definition.function)]

[(enumerator name: (_) @local.definition.var) (preproc_def name: (_) @local.definition.var) (preproc_function_def name: (_) @local.definition.var)]

; --- what mentions a name --------------------------------------------------
;
; Every name-shaped token is a reference until something more specific claims
; it. The locals engine resolves each against the definitions in scope, so
; over-capturing here is cheap and under-capturing is not.

[(identifier) (type_identifier)] @local.reference
