[workspace]
members = [
    "crates/treebank-cli",
    "crates/treebank-core",
    "crates/treebank-corpus",
    "crates/treebank-bash",
    "crates/treebank-java",
    "crates/treebank-lang",
    "crates/treebank-oracle",
    "crates/treebank-preprocessing",
    "crates/treebank-python",
    "crates/treebank-rust",
    "crates/treebank-typescript",
]
resolver = "2"
