// GENERATED by treebank-sdf3 from the module's layout constraints. Do not
// edit: the lowering regenerates it. See src/scanner.rs for the rules.

#include "tree_sitter/parser.h"
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

enum TokenType {
  NEWLINE,
  INDENT,
  DEDENT,
  ERROR_SENTINEL,
};

static bool is_layout(int32_t c) {
  return c == ' ' || c == '\t' || c == '\n' || c == '\r';
}

static bool is_break(int32_t c) {
  return c == '\n' || c == '\r';
}

// The character that opens a line comment in LAYOUT, or 0.
static const int32_t COMMENT_OPEN = '#';

// The open block columns, outermost first. Column 0 is always open.
#define MAX_DEPTH 64
typedef struct {
  uint16_t depth;
  uint16_t cols[MAX_DEPTH];
} Indent;

static bool on_stack(const Indent *s, int col) {
  for (unsigned i = 0; i < s->depth; i++) {
    if (s->cols[i] == col) return true;
  }
  return false;
}

// Past a line break: the column of the next line that holds a token,
// looking over blank lines and comment lines, or -1 at end of input. Moves
// the lexer without marking, so the caller's token ends where it chose.
static int next_line_column(TSLexer *lexer) {
  for (;;) {
    int col = 0;
    for (;;) {
      if (lexer->lookahead == ' ') {
        col++;
      } else if (lexer->lookahead == '\t') {
        col++;
      } else {
        break;
      }
      lexer->advance(lexer, false);
    }
    if (lexer->lookahead == 0) return -1;
    if (COMMENT_OPEN && lexer->lookahead == COMMENT_OPEN) {
      while (lexer->lookahead != 0 && !is_break(lexer->lookahead)) lexer->advance(lexer, false);
      if (lexer->lookahead == 0) return -1;
    }
    if (is_break(lexer->lookahead)) {
      if (lexer->lookahead == '\r') lexer->advance(lexer, false);
      if (lexer->lookahead == '\n') lexer->advance(lexer, false);
      continue;
    }
    return col;
  }
}

void *tree_sitter_pyish_external_scanner_create(void) {
  Indent *s = calloc(1, sizeof(Indent));
  s->depth = 1;
  return s;
}
void tree_sitter_pyish_external_scanner_destroy(void *payload) { free(payload); }
unsigned tree_sitter_pyish_external_scanner_serialize(void *payload, char *buffer) {
  Indent *s = payload;
  unsigned n = sizeof(uint16_t) * (1 + s->depth);
  memcpy(buffer, s, n);
  return n;
}
void tree_sitter_pyish_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  Indent *s = payload;
  s->depth = 1;
  s->cols[0] = 0;
  if (length >= sizeof(uint16_t)) memcpy(s, buffer, length);
}

bool tree_sitter_pyish_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid) {
  (void)payload;
  // During error recovery every symbol is marked valid (the sentinel is
  // never produced, so seeing it valid is the tell).
  bool recovery = valid[ERROR_SENTINEL];

  bool space_before = false;
  while (is_layout(lexer->lookahead) && !is_break(lexer->lookahead)) {
    lexer->advance(lexer, true);
    space_before = true;
  }
  int32_t c = lexer->lookahead;

  // Block structure by column. `_newline` is the line break that ends a
  // statement; `_indent` is the break that opens a block, and consumes it;
  // `_dedent` is zero-width, one per closed block, at the first token of
  // the line that closed them. A deeper line that opens no block is a
  // continuation and gets no token at all.
  Indent *s = payload;
  bool want_nl = valid[NEWLINE] || recovery;
  bool want_in = valid[INDENT] && !recovery;
  bool want_de = valid[DEDENT] || recovery;
  if (want_nl || want_in || want_de) {
    int top = s->cols[s->depth - 1];
    bool at_break = c == 0 || is_break(c);
    // A comment before the break is an extra the parser wants to see;
    // come back for the break after it.
    if (COMMENT_OPEN && c == COMMENT_OPEN && (want_nl || want_in)) return false;
    lexer->mark_end(lexer);
    int col;
    if (at_break) {
      if (c == '\r') lexer->advance(lexer, false);
      if (lexer->lookahead == '\n') lexer->advance(lexer, false);
      if (want_nl || want_in) lexer->mark_end(lexer);
      col = next_line_column(lexer);
    } else if (COMMENT_OPEN && c == COMMENT_OPEN) {
      // A comment line while only `_dedent` is wanted: decide by the line
      // after it, and leave the comment to the parser.
      while (lexer->lookahead != 0 && !is_break(lexer->lookahead)) lexer->advance(lexer, false);
      if (lexer->lookahead == '\r') lexer->advance(lexer, false);
      if (lexer->lookahead == '\n') lexer->advance(lexer, false);
      col = next_line_column(lexer);
    } else {
      col = (int)lexer->get_column(lexer);
    }
    if (at_break && want_in && col > top && s->depth < MAX_DEPTH) {
      s->cols[s->depth++] = (uint16_t)col;
      lexer->result_symbol = INDENT;
      return true;
    }
    if (at_break && want_nl) {
      if (col > top) return false;  // a continuation line: the offside rule
      lexer->result_symbol = NEWLINE;
      return true;
    }
    if (want_de && s->depth > 1 && col < top) {
      if (col >= 0 && !on_stack(s, col)) {
        // A dedent to a column no open block has: `else` off its `if`.
        lexer->result_symbol = ERROR_SENTINEL;
        return true;
      }
      s->depth--;
      lexer->result_symbol = DEDENT;
      return true;
    }
    if (at_break) return false;
  }
  (void)space_before;
  (void)c;
  return false;
}
