; GENERATED by `treebank queries --write` from queries/locals.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; ruby's own node types. Edit queries/locals.scm and regenerate, or the next
; --check will fail.

; --- where names live ------------------------------------------------------
;
; A scope is anything that can contain a binding without leaking it. What
; counts differs per language -- a block, a function body, a module, a `do`
; end -- and each grammar declares its own members.

[(brace_block) (class_definition) (do_block) (function_definition) (lambda) (module_definition) (program) (singleton_class)] @local.scope

; --- what introduces a name ------------------------------------------------
;
; The capture goes on the NAME, not on the construct: an editor renames the
; identifier, and needs the range of the thing it would rewrite. Members that
; have no `name` field are dropped when this is expanded, which is why a
; language whose bindings are positional loses those patterns rather than
; producing a pattern that cannot match.

[(function_definition name: (_) @local.definition.function)]

[(block_parameter name: (_) @local.definition.var) (class_definition name: (_) @local.definition.var) (double_star_parameter name: (_) @local.definition.var) (function_definition name: (_) @local.definition.var) (keyword_parameter name: (_) @local.definition.var) (module_definition name: (_) @local.definition.var) (parameter name: (_) @local.definition.var) (star_parameter name: (_) @local.definition.var)]

; A parameter is a definition, and the one place a caller's name meets the
; callee's. bash has no term for it: a bash function takes `$1`, not a named
; parameter, so this is omitted there rather than dropped from everyone.
(_parameter name: (_) @local.definition.parameter)

; --- what mentions a name --------------------------------------------------
;
; Every name-shaped token is a reference until something more specific claims
; it. The locals engine resolves each against the definitions in scope, so
; over-capturing here is cheap and under-capturing is not.

[(class_variable) (constant) (global_variable) (identifier) (instance_variable) (scope_resolution) (self) (setter_method_name)] @local.reference
