; GENERATED by treebank-sdf3 from the scope/binds/refers attributes of
; jsish.sdf3, in treebank's locals vocabulary. bindings.json is the exact
; data; this is the query-dialect view of it.

; --- where names live
[(program) (function) (block)] @local.scope

; --- what introduces a name
(function name: (id) @local.definition.function
  (#set! definition.function.scope "parent"))

; bindings.json: scope = function. The dialect has no way to say it.
(var name: (id) @local.definition.var)

(let name: (id) @local.definition.var)

(param name: (id) @local.definition.parameter)

; --- what mentions a name
(id) @local.reference
