//! Generate each grammar's query files from one vocabulary-level source.
//!
//! Every tree-sitter grammar in the wild ships a hand-written
//! `queries/highlights.scm` naming its own node types, and every one of them
//! drifts from its neighbours because nothing holds them together. Treebank
//! has something that does: a supertype is threaded through the productions
//! and a facet is declared in `roles.json`, so `(_callable)` means the same
//! thing in nine grammars and can be written once.
//!
//! What an editor loads still has to be per-grammar, because a facet is not a
//! rule and tree-sitter cannot match one. So `queries/highlights.scm` at the
//! repository root is the SOURCE, and `crates/treebank-<lang>/queries/` holds
//! DERIVED files -- facets expanded into that grammar's own members, through
//! the same `expand_with_types` a consumer gets from `Pack::query`.
//!
//! Derived rather than duplicated is the point. `--check` regenerates and
//! fails on a difference, so the per-grammar files cannot drift from the
//! source or from each other, which is exactly what goes wrong everywhere
//! else.

use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

use treebank::expand::expand_with_types;
use treebank::node_types::NodeTypes;
use treebank::roles::RolesManifest;
use treebank_lang::LangName;

/// Written into every generated file. A query file is exactly the kind of
/// thing someone fixes in place at 2am without noticing where it came from.
const HEADER: &str = "\
; GENERATED by `treebank queries --write` from queries/%NAME% -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; %LANG%'s own node types. Edit queries/%NAME% and regenerate, or the next
; --check will fail.
";

/// The grammars that own a crate, each once. `LangName::ALL` includes
/// dialects that route to another grammar -- javascript to typescript -- and
/// generating that pair twice would write one file twice.
fn grammars() -> Vec<LangName> {
    let mut seen: Vec<LangName> = Vec::new();
    for lang in LangName::ALL {
        let grammar = lang.grammar();
        if !seen.contains(&grammar) {
            seen.push(grammar);
        }
    }
    seen.sort_by_key(|l| l.as_str());
    seen
}

/// The `.scm` files under the source directory, by file name.
fn sources(dir: &Path) -> Result<BTreeMap<String, String>> {
    let mut out = BTreeMap::new();
    let entries = std::fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))?;
    for entry in entries {
        let path = entry?.path();
        if path.extension().is_some_and(|e| e == "scm") {
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let text = std::fs::read_to_string(&path)
                .with_context(|| format!("reading {}", path.display()))?;
            out.insert(name, text);
        }
    }
    if out.is_empty() {
        bail!("no .scm files in {}", dir.display());
    }
    Ok(out)
}

/// What `<grammar>/queries/<name>` should contain.
fn render(
    name: &str,
    lang: LangName,
    source: &str,
    crates_dir: &Path,
) -> Result<(String, Vec<String>)> {
    let dir = crates_dir.join(lang.grammar_crate());
    let roles: RolesManifest = {
        let path = dir.join("roles.json");
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;
        serde_json::from_str(&text).with_context(|| format!("parsing {}", path.display()))?
    };
    let node_types = NodeTypes::load(&dir.join("src/node-types.json"))
        .with_context(|| format!("reading node-types.json for {}", lang.as_str()))?;

    // Terms this grammar delivers, either tier. A supertype is a rule with
    // subtypes; a facet is a list in roles.json.
    let mut known: HashSet<String> = roles.facets.keys().cloned().collect();
    known.extend(node_types.supertypes.keys().cloned());

    // The source's own preamble explains the source -- that it is the file to
    // edit, what the two tiers are. Repeating it above an expanded copy tells
    // a reader the opposite of the truth, so the leading comment block is
    // dropped and the generated header speaks instead. Section comments
    // further down survive: those describe the patterns, which are still here.
    let body = strip_leading_comment(source);
    let (body, dropped) = apply_conditionals(body, &known);
    let body = &body;

    // Expanded a block at a time rather than whole-file, so a pattern this
    // grammar cannot express can be omitted and NAMED. Expansion is local to
    // each pattern, so the result is the same as expanding the whole file.
    //
    // The one tolerated failure is a field constraint no member can satisfy:
    // C's parameters are declarators with no `name` field, so
    // `(_parameter name: (_))` filters every member away. That is a fact
    // about C rather than a mistake in the query, and the alternative --
    // failing the build for all nine -- would mean writing to the least
    // expressive grammar. Every other expansion error still propagates.
    let mut pieces: Vec<String> = Vec::new();
    let mut inexpressible: Vec<String> = Vec::new();
    for block in body.split("\n\n") {
        match expand_with_types(block, &roles.facets, Some(&node_types)) {
            Ok(expanded) => pieces.push(expanded),
            Err(e) => {
                let message = e.to_string();
                if let Some(term) = message
                    .strip_prefix("facet `")
                    .and_then(|r| r.split('`').next())
                    .filter(|_| message.contains("no member satisfies"))
                {
                    if !inexpressible.contains(&term.to_string()) {
                        inexpressible.push(term.to_string());
                    }
                    continue;
                }
                return Err(e).with_context(|| format!("expanding {name} for {}", lang.as_str()));
            }
        }
    }
    let expanded = pieces.join("\n\n");

    let mut header = HEADER
        .replace("%NAME%", name)
        .replace("%LANG%", lang.as_str());
    // Named in the file rather than only in the tool's output: someone reading
    // this grammar's queries should see what it does not have without running
    // anything. The two reasons are different and are not run together --
    // "no such term" and "the term is here but no member takes that field"
    // point at different work.
    if !dropped.is_empty() {
        header.push_str(&format!(
            ";\n; Omitted: {} has no {}.\n",
            lang.as_str(),
            dropped.join(", ")
        ));
    }
    if !inexpressible.is_empty() {
        header.push_str(&format!(
            ";\n; Omitted: {} has {}, but no member of it takes\n; the field the pattern asks for.\n",
            lang.as_str(),
            inexpressible.join(", ")
        ));
    }
    let mut reported = dropped;
    reported.extend(inexpressible);
    Ok((format!("{header}\n{expanded}"), reported))
}

/// A pattern that only some grammars can express.
///
/// `_scope`, `_binding` and `_identifier` exist everywhere, but `_parameter`
/// does not: bash functions take `$1`, not a named parameter, so there is no
/// term for one and a pattern naming it cannot compile there. Requiring every
/// pattern to be universal would mean dropping parameter definitions from the
/// eight grammars that DO have them, which is the worse trade.
///
/// So a block may be marked:
///
/// ```scm
/// ; treebank: only-if _parameter
/// (_parameter name: (_) @local.definition.parameter)
/// ```
///
/// and is omitted for a grammar lacking any named term. Omissions are
/// reported, and written into the generated file's header: a pattern that
/// vanishes silently is how a grammar ends up quietly worse than its
/// neighbours, which is the failure this whole arrangement exists to prevent.
///
/// The block runs from the directive to the next blank line.
const ONLY_IF: &str = "; treebank: only-if";

fn apply_conditionals(source: &str, known: &HashSet<String>) -> (String, Vec<String>) {
    let mut out = String::with_capacity(source.len());
    let mut dropped: Vec<String> = Vec::new();
    let mut lines = source.lines().peekable();

    while let Some(line) = lines.next() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix(ONLY_IF) else {
            out.push_str(line);
            out.push('\n');
            continue;
        };
        let wanted: Vec<String> = rest
            .split_whitespace()
            .map(|t| {
                t.trim_matches(|c: char| !(c.is_alphanumeric() || c == '_'))
                    .to_string()
            })
            .filter(|t| !t.is_empty())
            .collect();
        let missing: Vec<String> = wanted
            .iter()
            .filter(|t| !known.contains(*t))
            .cloned()
            .collect();

        // The directive line never reaches the output either way.
        let keep = missing.is_empty();
        for term in missing {
            if !dropped.contains(&term) {
                dropped.push(term);
            }
        }
        while let Some(next) = lines.peek() {
            if next.trim().is_empty() {
                break;
            }
            let next = lines.next().unwrap();
            if keep {
                out.push_str(next);
                out.push('\n');
            }
        }
        // A dropped block leaves its blank line behind, which would stack up.
        if !keep {
            while lines.peek().is_some_and(|l| l.trim().is_empty()) {
                lines.next();
            }
        }
    }
    (out, dropped)
}

/// Everything after the FIRST block of `;` comments, and the blank lines
/// under it. Only the first block: the section comments further down describe
/// patterns that are still in the generated file, and belong with them.
fn strip_leading_comment(source: &str) -> &str {
    let mut rest = source;
    let advance = |rest: &mut &str| -> bool {
        match rest.find('\n') {
            Some(n) => {
                *rest = &rest[n + 1..];
                true
            }
            None => {
                *rest = "";
                false
            }
        }
    };
    while rest
        .lines()
        .next()
        .unwrap_or("")
        .trim_start()
        .starts_with(';')
    {
        if !advance(&mut rest) {
            return "";
        }
    }
    while rest.lines().next().is_some_and(|l| l.trim().is_empty()) {
        if !advance(&mut rest) {
            return "";
        }
    }
    rest
}

pub fn run(source_dir: &Path, crates_dir: &Path, check: bool) -> Result<()> {
    let sources = sources(source_dir)?;
    let mut stale: Vec<String> = Vec::new();
    let mut written = 0usize;

    for lang in grammars() {
        let out_dir = crates_dir.join(lang.grammar_crate()).join("queries");

        // Compiled against the real grammar, on both paths. Matching the
        // source only proves the copies agree; a source that expands into an
        // impossible pattern would regenerate perfectly and be equally broken
        // in all nine. This is also where a term threaded in eight grammars
        // and forgotten in the ninth surfaces -- an absent supertype is just
        // an unknown node name, and only tree-sitter can say so.
        let language = crate::grammar::load(&crates_dir.join(lang.grammar_crate()))
            .with_context(|| format!("loading the {} grammar", lang.as_str()))?
            .0;

        for (name, source) in &sources {
            let (want, _) = render(name, lang, source, crates_dir)?;
            let path = out_dir.join(name);

            tree_sitter::Query::new(&language, &want).map_err(|e| {
                anyhow::anyhow!(
                    "queries/{name} does not compile against {}: {e:?}",
                    lang.as_str()
                )
            })?;

            let have = std::fs::read_to_string(&path).ok();
            if have.as_deref() == Some(want.as_str()) {
                continue;
            }
            if check {
                stale.push(format!(
                    "  {} is {}",
                    path.display(),
                    if have.is_none() {
                        "missing"
                    } else {
                        "out of date"
                    }
                ));
                continue;
            }
            std::fs::create_dir_all(&out_dir)
                .with_context(|| format!("creating {}", out_dir.display()))?;
            std::fs::write(&path, &want).with_context(|| format!("writing {}", path.display()))?;
            written += 1;
        }
    }

    if check {
        if !stale.is_empty() {
            bail!(
                "{} generated query file(s) do not match queries/:\n{}\n\nRun `treebank queries \
                 --write`.",
                stale.len(),
                stale.join("\n")
            );
        }
        println!(
            "queries: {} file(s) x {} grammars are current and compile",
            sources.len(),
            grammars().len()
        );
    } else {
        println!(
            "queries: wrote {written} file(s) across {} grammars",
            grammars().len()
        );
    }
    Ok(())
}

/// Where the generated file for one grammar lives, for tests and callers.
pub fn generated_path(crates_dir: &Path, lang: LangName, name: &str) -> PathBuf {
    crates_dir
        .join(lang.grammar_crate())
        .join("queries")
        .join(name)
}

/// Every source example in a tree-sitter corpus file.
///
/// The format is a `===` fence around a name, the source, then a `---` fence
/// and the expected tree. Only the source half is wanted here.
fn corpus_examples(text: &str) -> Vec<String> {
    let fence = |line: &str, c: char| {
        let t = line.trim_end();
        t.len() >= 3 && t.chars().all(|ch| ch == c)
    };
    let mut out = Vec::new();
    let lines: Vec<&str> = text.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        if !fence(lines[i], '=') {
            i += 1;
            continue;
        }
        // fence, name(s), fence, then the source until a `---` fence.
        let mut j = i + 1;
        while j < lines.len() && !fence(lines[j], '=') {
            j += 1;
        }
        if j >= lines.len() {
            break;
        }
        let mut k = j + 1;
        let start = k;
        while k < lines.len() && !fence(lines[k], '-') {
            k += 1;
        }
        if k <= lines.len() && start < k {
            out.push(lines[start..k].join("\n"));
        }
        // Continue after the expected tree, at the next `===`.
        i = k + 1;
    }
    out
}

fn corpus_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(dir.join("test/corpus")) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "txt") {
            out.push(path);
        }
    }
    out.sort();
    out
}

/// How much of a parse the universal file actually colours.
///
/// Reported per grammar over that grammar's own corpus, because the claim
/// "one file highlights nine languages" is worth a number rather than a
/// demonstration on a five-line sample. A named node is the unit: anonymous
/// tokens are keywords and punctuation, which no vocabulary term reaches and
/// which a per-grammar supplement is for.
pub fn coverage(crates_dir: &Path, name: &str) -> Result<()> {
    println!("{name}\n");
    println!(
        "{:<12} {:>9} {:>12} {:>12}  {}",
        "grammar", "examples", "named nodes", "captured", "share"
    );
    let mut total_named = 0usize;
    let mut total_captured = 0usize;

    for lang in grammars() {
        let dir = crates_dir.join(lang.grammar_crate());
        let path = generated_path(crates_dir, lang, name);
        let scm = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}; run `treebank queries` first", path.display()))?;

        let (language, _) = crate::grammar::load(&dir)
            .with_context(|| format!("loading the {} grammar", lang.as_str()))?;
        let query = tree_sitter::Query::new(&language, &scm)
            .with_context(|| format!("compiling {}", path.display()))?;
        let mut parser = tree_sitter::Parser::new();
        parser.set_language(&language)?;

        let (mut named, mut captured, mut examples) = (0usize, 0usize, 0usize);
        for file in corpus_files(&dir) {
            let Ok(text) = std::fs::read_to_string(&file) else {
                continue;
            };
            for source in corpus_examples(&text) {
                let Some(tree) = parser.parse(&source, None) else {
                    continue;
                };
                examples += 1;

                let mut hit: HashSet<usize> = HashSet::new();
                let mut cursor = tree_sitter::QueryCursor::new();
                {
                    use tree_sitter::StreamingIterator;
                    let mut matches = cursor.matches(&query, tree.root_node(), source.as_bytes());
                    while let Some(m) = matches.next() {
                        for capture in m.captures {
                            hit.insert(capture.node.id());
                        }
                    }
                }

                let mut walk = tree.walk();
                let mut stack = vec![tree.root_node()];
                while let Some(node) = stack.pop() {
                    if node.is_named() {
                        named += 1;
                        if hit.contains(&node.id()) {
                            captured += 1;
                        }
                    }
                    for child in node.children(&mut walk) {
                        stack.push(child);
                    }
                }
            }
        }
        total_named += named;
        total_captured += captured;
        let share = if named == 0 {
            0.0
        } else {
            captured as f64 * 100.0 / named as f64
        };
        println!(
            "{:<12} {examples:>9} {named:>12} {captured:>12}  {share:>5.1}%",
            lang.as_str()
        );
    }

    let share = if total_named == 0 {
        0.0
    } else {
        total_captured as f64 * 100.0 / total_named as f64
    };
    println!(
        "\n{} named nodes, {} captured by one file: {share:.1}%",
        total_named, total_captured
    );
    Ok(())
}
