; GENERATED by `treebank queries --write` from queries/highlights.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; zig's own node types. Edit queries/highlights.scm and regenerate, or the next
; --check will fail.

; --- the leaves a reader looks at first -----------------------------------

[(container_doc_comment) (doc_comment) (line_comment)] @comment
[(multiline_string) (string)] @string
(_literal) @number

; --- names ----------------------------------------------------------------
;
; `_identifier` is every name-shaped token, so it is the fallback that later
; patterns narrow.

[(builtin_identifier) (identifier)] @variable

; --- things that are called ------------------------------------------------

[(function_declaration) (function_type) (test_declaration)] @function
(_invocation) @function.call

; --- control flow ----------------------------------------------------------
;
; These capture the whole construct rather than its keyword: the keyword is
; an anonymous token, and an anonymous token has no vocabulary term. A
; per-grammar supplement is where `if` and `while` themselves get coloured.

(_loop) @keyword.repeat
(_branch) @keyword.conditional
(_jump) @keyword.return
(_directive) @keyword.import
