; GENERATED by `treebank queries` from queries/locals.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; zig's own node types. Edit queries/locals.scm and regenerate, or the next
; --check will fail.

; --- where names live ------------------------------------------------------
;
; A scope is anything that can contain a binding without leaking it. What
; counts differs per language -- a block, a function body, a module, a `do`
; end -- and each grammar declares its own members.

[(block) (container_declaration) (function_declaration) (source_file) (test_declaration)] @local.scope

; --- what introduces a name ------------------------------------------------
;
; The capture goes on the NAME, not on the construct: an editor renames the
; identifier, and needs the range of the thing it would rewrite. Members that
; have no `name` field are dropped when this is expanded, which is why a
; language whose bindings are positional loses those patterns rather than
; producing a pattern that cannot match.

[(function_declaration name: (_) @local.definition.function) (function_type name: (_) @local.definition.function) (test_declaration name: (_) @local.definition.function)]

[(container_field name: (_) @local.definition.var) (function_declaration name: (_) @local.definition.var) (parameter name: (_) @local.definition.var) (payload name: (_) @local.definition.var) (variable_declaration name: (_) @local.definition.var)]

; A parameter is a definition, and the one place a caller's name meets the
; callee's. bash has no term for it: a bash function takes `$1`, not a named
; parameter, so this is omitted there rather than dropped from everyone.
[(parameter name: (_) @local.definition.parameter)]

; --- what mentions a name --------------------------------------------------
;
; Every name-shaped token is a reference until something more specific claims
; it. The locals engine resolves each against the definitions in scope, so
; over-capturing here is cheap and under-capturing is not.

[(builtin_identifier) (identifier)] @local.reference
