; GENERATED by treebank-sdf3 from the scope/binds/refers attributes of
; rust/2024.sdf3, in treebank's locals vocabulary. bindings.json is the exact
; data; this is the query-dialect view of it.

; --- where names live
[(program) (fn) (block)] @local.scope

; --- what introduces a name
(fn name: (id) @local.definition.function
  (#set! definition.function.scope "parent"))

(param name: (id) @local.definition.parameter)

(let pattern: (id) @local.definition.var)

(let_mut pattern: (id) @local.definition.var)

; --- what mentions a name
(id) @local.reference
