; GENERATED by `treebank queries --write` from queries/highlights.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; yaml's own node types. Edit queries/highlights.scm and regenerate, or the next
; --check will fail.
;
; Omitted: yaml has no _callable, _invocation, _loop, _branch, _jump.

; --- the leaves a reader looks at first -----------------------------------

[(comment)] @comment
[(block_scalar) (double_quote_scalar) (single_quote_scalar)] @string
(_literal) @number

; --- names ----------------------------------------------------------------
;
; `_identifier` is every name-shaped token, so it is the fallback that later
; patterns narrow.

[(anchor_name) (directive_name)] @variable

; --- things that are called ------------------------------------------------
;
; Guarded, because not every language treebank parses computes. YAML has no
; callable and no invocation, and a pattern naming a term its grammar does
; not declare is a QueryError at load time rather than a zero-match, so the
; block is dropped for the grammars that lack the term instead of the file
; failing to compile for them.

; --- control flow ----------------------------------------------------------
;
; These capture the whole construct rather than its keyword: the keyword is
; an anonymous token, and an anonymous token has no vocabulary term. A
; per-grammar supplement is where `if` and `while` themselves get coloured.
;
; Guarded for the same reason as the block above: a data language alters no
; sequential execution because it has none.

; And guarded once more, for a language that computes but never reaches
; outside its own file: HCL's `module` block is a block, and what its
; `source` means is the calling application's business rather than the
; syntax's.
(_directive) @keyword.import
