; GENERATED by `treebank queries` from queries/highlights.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; yaml's own node types. Edit queries/highlights.scm and regenerate, or the next
; --check will fail.
;
; Omitted: yaml has no _callable, _invocation, _loop, _branch, _jump.

; --- the leaves a reader looks at first -----------------------------------
;
; Guarded, because a comment is not universal either. JSON has no comment
; syntax at all — RFC 8259 defines none, and a grammar that declared
; `_comment` would be a grammar for JSONC.

[(comment)] @comment

; `_literal` BEFORE `_string`, and the order is the whole of it: the last
; matching pattern wins, and the two terms overlap wherever a language has a
; string literal that is also fully determined by its own text. In YAML they
; overlap completely — `_literal` is every scalar and `_string` is the three
; that are always strings — so with `_literal` last, `"quoted"` matched both
; and rendered as a NUMBER. Every quoted scalar in the language did.
(_literal) @number
[(block_scalar) (double_quote_scalar) (single_quote_scalar)] @string

; --- the key of a pair ------------------------------------------------------
;
; A mapping key is not a value and should not be coloured like one. There is
; no vocabulary TERM for a key — `_clause` is the subordinate piece and the
; key is a field on it — so this reaches it through the field, which is also
; what makes it self-limiting: expansion drops the members that have no
; `key`, so a language whose clauses are `elif` and `case` contributes
; nothing here and only the mapping-shaped ones do.

[(block_mapping_pair key: (_) @property) (flow_pair key: (_) @property)]

; --- names ----------------------------------------------------------------
;
; `_identifier` is every name-shaped token, so it is the fallback that later
; patterns narrow. Guarded because JSON has no identifiers: the thing in a
; naming position there is a string literal, which `_string` already claims.

[(anchor_name) (directive_name)] @variable

; --- types ------------------------------------------------------------------
;
; After `_identifier`, so a name in type position is coloured as a type
; rather than as the variable the broader pattern already claimed. Guarded
; because python declares no `_type` — its annotations are ordinary
; expressions — and YAML is what made the omission visible: a tag is the one
; piece of YAML syntax that says what a node IS, and nothing coloured it.

(_type) @type

; --- things that are called ------------------------------------------------
;
; Guarded, because not every language treebank parses computes. YAML has no
; callable and no invocation, and a pattern naming a term its grammar does
; not declare is a QueryError at load time rather than a zero-match, so the
; block is dropped for the grammars that lack the term instead of the file
; failing to compile for them.

; --- control flow ----------------------------------------------------------
;
; These capture the whole construct rather than its keyword: the keyword is
; an anonymous token, and an anonymous token has no vocabulary term. A
; per-grammar supplement is where `if` and `while` themselves get coloured.
;
; Guarded for the same reason as the block above: a data language alters no
; sequential execution because it has none.

; And guarded once more, for two languages rather than one. HCL computes
; but never reaches outside its own file: its `module` block is a block,
; and what the `source` inside it means is the calling application's
; business rather than the syntax's. JSON does not compute at all — there
; is no compilation unit for a directive to affect, and nothing to
; compile.
(_directive) @keyword.import
