// GENERATED by treebank-sdf3 from the module's layout constraints. Do not
// edit: the lowering regenerates it. See src/scanner.rs for the rules.

#include "tree_sitter/parser.h"
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

enum TokenType {
  QUOTE,
  ESCAPE_SEQUENCE,
  QCHUNK,
  HCHUNK,
  HEREDOC_END,
  DIR_ELSE,
  DIR_ENDIF,
  DIR_ENDFOR,
  NL,
  HEREDOC_START,
  ERROR_SENTINEL,
};

static bool is_layout(int32_t c) {
  return c == ' ' || c == '\t' || c == '\r' || c == '\n';
}

static bool is_break(int32_t c) {
  return c == '\n' || c == '\r';
}

// The character that opens a line comment in LAYOUT, or 0.
static const int32_t COMMENT_OPEN = 0;

// ---- Scanner-owned lexical sorts: the module's automaton, simulated ----

// The character that stands for end of input in a guard.
#define EOF_CP 0x10FFFF

typedef struct { int32_t lo, hi; } Range;
typedef struct { const Range *ranges; uint16_t n; bool negated; } Class;
static const Range R_0[] = {{34, 34}};
static const Range R_1[] = {{92, 92}};
static const Range R_2[] = {{110, 110}, {114, 114}, {116, 116}, {34, 34}, {92, 92}};
static const Range R_3[] = {{117, 117}};
static const Range R_4[] = {{48, 57}, {97, 102}, {65, 70}};
static const Range R_5[] = {{85, 85}};
static const Range R_6[] = {{34, 34}, {92, 92}, {36, 36}, {37, 37}, {10, 10}, {13, 13}};
static const Range R_7[] = {{36, 36}};
static const Range R_8[] = {{123, 123}};
static const Range R_9[] = {{37, 37}};
static const Range R_10[] = {{36, 36}, {37, 37}};
static const Range R_11[] = {{36, 36}, {37, 37}, {10, 10}, {13, 13}};
static const Range R_12[] = {{13, 13}};
static const Range R_13[] = {{10, 10}};
static const Range R_14[] = {{10, 10}, {13, 13}};
static const Range R_15[] = {{1114111, 1114111}};
static const Range R_16[] = {{32, 32}, {9, 9}};
static const Range R_17[] = {{97, 122}, {65, 90}, {48, 57}, {95, 95}, {45, 45}};
static const Range R_18[] = {{126, 126}};
static const Range R_19[] = {{32, 32}, {9, 9}, {13, 13}, {10, 10}};
static const Range R_20[] = {{101, 101}};
static const Range R_21[] = {{108, 108}};
static const Range R_22[] = {{115, 115}};
static const Range R_23[] = {{125, 125}};
static const Range R_24[] = {{110, 110}};
static const Range R_25[] = {{100, 100}};
static const Range R_26[] = {{105, 105}};
static const Range R_27[] = {{102, 102}};
static const Range R_28[] = {{111, 111}};
static const Range R_29[] = {{114, 114}};
static const Range R_30[] = {{60, 60}};
static const Range R_31[] = {{45, 45}};
static const Class CLASSES[] = {
  {R_0, 1, false},
  {R_1, 1, false},
  {R_2, 5, false},
  {R_3, 1, false},
  {R_4, 3, false},
  {R_5, 1, false},
  {R_6, 6, true},
  {R_7, 1, false},
  {R_8, 1, false},
  {R_9, 1, false},
  {R_10, 2, false},
  {R_11, 4, true},
  {R_12, 1, false},
  {R_13, 1, false},
  {R_14, 2, true},
  {R_15, 1, false},
  {R_16, 2, false},
  {R_17, 5, false},
  {R_18, 1, false},
  {R_19, 4, false},
  {R_20, 1, false},
  {R_21, 1, false},
  {R_22, 1, false},
  {R_23, 1, false},
  {R_24, 1, false},
  {R_25, 1, false},
  {R_26, 1, false},
  {R_27, 1, false},
  {R_28, 1, false},
  {R_29, 1, false},
  {R_30, 1, false},
  {R_31, 1, false},
};

typedef struct { uint16_t target; int16_t cls; } Edge;
typedef struct { uint16_t target; int16_t guard[4]; uint8_t n_guard; uint8_t tag; } Eps;
typedef struct { const Edge *edges; uint8_t n_edges; const Eps *eps; uint8_t n_eps; bool accept; uint8_t tok; } State;
static const Edge E_0[] = {{1, 0}};
static const Edge E_2[] = {{4, 1}};
static const Edge E_4[] = {{3, 2}, {5, 3}, {9, 5}};
static const Edge E_5[] = {{6, 4}};
static const Edge E_6[] = {{7, 4}};
static const Edge E_7[] = {{8, 4}};
static const Edge E_8[] = {{3, 4}};
static const Edge E_9[] = {{10, 4}};
static const Edge E_10[] = {{11, 4}};
static const Edge E_11[] = {{12, 4}};
static const Edge E_12[] = {{13, 4}};
static const Edge E_13[] = {{14, 4}};
static const Edge E_14[] = {{15, 4}};
static const Edge E_15[] = {{16, 4}};
static const Edge E_16[] = {{3, 4}};
static const Eps P_17[] = {{19, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_19[] = {{20, 6}, {21, 7}, {23, 9}, {25, 10}};
static const Eps P_20[] = {{19, {-1, -1, -1, -1}, 0, 0}, {18, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_21[] = {{22, 7}};
static const Edge E_22[] = {{20, 8}};
static const Edge E_23[] = {{24, 9}};
static const Edge E_24[] = {{20, 8}};
static const Eps P_25[] = {{20, {8, -1, -1, -1}, 1, 0}};
static const Eps P_26[] = {{29, {-1, -1, -1, -1}, 0, 0}, {37, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_28[] = {{36, 12}};
static const Eps P_28[] = {{36, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_29[] = {{30, 11}, {31, 7}, {33, 9}, {35, 10}};
static const Eps P_29[] = {{28, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_30[] = {{29, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_31[] = {{32, 7}};
static const Edge E_32[] = {{30, 8}};
static const Edge E_33[] = {{34, 9}};
static const Edge E_34[] = {{30, 8}};
static const Eps P_35[] = {{30, {8, -1, -1, -1}, 1, 0}};
static const Edge E_36[] = {{27, 13}};
static const Edge E_37[] = {{38, 11}, {39, 7}, {41, 9}, {43, 10}};
static const Eps P_38[] = {{37, {-1, -1, -1, -1}, 0, 0}, {27, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_39[] = {{40, 7}};
static const Edge E_40[] = {{38, 8}};
static const Edge E_41[] = {{42, 9}};
static const Edge E_42[] = {{38, 8}};
static const Eps P_43[] = {{38, {8, -1, -1, -1}, 1, 0}};
static const Eps P_44[] = {{48, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_46[] = {{45, {14, 15, -1, -1}, 2, 0}};
static const Eps P_47[] = {{51, {-1, -1, -1, -1}, 0, 1}};
static const Edge E_48[] = {{49, 16}};
static const Eps P_48[] = {{47, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_49[] = {{48, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_50[] = {{55, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_51[] = {{53, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_52[] = {{50, {17, -1, -1, -1}, 1, 2}};
static const Edge E_53[] = {{54, 17}};
static const Eps P_54[] = {{53, {-1, -1, -1, -1}, 0, 0}, {52, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_55[] = {{56, 16}};
static const Eps P_55[] = {{46, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_56[] = {{55, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_57[] = {{60, 9}};
static const Edge E_59[] = {{61, 18}};
static const Eps P_59[] = {{61, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_60[] = {{59, 8}};
static const Eps P_61[] = {{63, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_62[] = {{66, 20}};
static const Edge E_63[] = {{64, 19}};
static const Eps P_63[] = {{62, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_64[] = {{63, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_65[] = {{70, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_66[] = {{67, 21}};
static const Edge E_67[] = {{68, 22}};
static const Edge E_68[] = {{65, 20}};
static const Edge E_69[] = {{72, 18}};
static const Eps P_69[] = {{72, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_70[] = {{71, 19}};
static const Eps P_70[] = {{69, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_71[] = {{70, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_72[] = {{58, 23}};
static const Edge E_73[] = {{76, 9}};
static const Edge E_75[] = {{77, 18}};
static const Eps P_75[] = {{77, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_76[] = {{75, 8}};
static const Eps P_77[] = {{79, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_78[] = {{82, 20}};
static const Edge E_79[] = {{80, 19}};
static const Eps P_79[] = {{78, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_80[] = {{79, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_81[] = {{87, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_82[] = {{83, 24}};
static const Edge E_83[] = {{84, 25}};
static const Edge E_84[] = {{85, 26}};
static const Edge E_85[] = {{81, 27}};
static const Edge E_86[] = {{89, 18}};
static const Eps P_86[] = {{89, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_87[] = {{88, 19}};
static const Eps P_87[] = {{86, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_88[] = {{87, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_89[] = {{74, 23}};
static const Edge E_90[] = {{93, 9}};
static const Edge E_92[] = {{94, 18}};
static const Eps P_92[] = {{94, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_93[] = {{92, 8}};
static const Eps P_94[] = {{96, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_95[] = {{99, 20}};
static const Edge E_96[] = {{97, 19}};
static const Eps P_96[] = {{95, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_97[] = {{96, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_98[] = {{105, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_99[] = {{100, 24}};
static const Edge E_100[] = {{101, 25}};
static const Edge E_101[] = {{102, 27}};
static const Edge E_102[] = {{103, 28}};
static const Edge E_103[] = {{98, 29}};
static const Edge E_104[] = {{107, 18}};
static const Eps P_104[] = {{107, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_105[] = {{106, 19}};
static const Eps P_105[] = {{104, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_106[] = {{105, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_107[] = {{91, 23}};
static const Edge E_108[] = {{110, 12}};
static const Eps P_108[] = {{110, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_110[] = {{111, 13}};
static const Eps P_111[] = {{112, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_112[] = {{115, {-1, -1, -1, -1}, 0, 0}, {109, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_113[] = {{112, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_114[] = {{117, 12}};
static const Eps P_114[] = {{117, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_115[] = {{116, 16}};
static const Eps P_115[] = {{114, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_116[] = {{115, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_117[] = {{113, 13}};
static const Edge E_118[] = {{121, 30}};
static const Edge E_120[] = {{122, 31}};
static const Eps P_120[] = {{122, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_121[] = {{120, 30}};
static const Eps P_122[] = {{124, {-1, -1, -1, -1}, 0, 1}};
static const Edge E_123[] = {{128, 12}};
static const Eps P_123[] = {{128, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_124[] = {{126, {-1, -1, -1, -1}, 0, 0}};
static const Eps P_125[] = {{123, {17, -1, -1, -1}, 1, 2}};
static const Edge E_126[] = {{127, 17}};
static const Eps P_127[] = {{126, {-1, -1, -1, -1}, 0, 0}, {125, {-1, -1, -1, -1}, 0, 0}};
static const Edge E_128[] = {{119, 13}};
#define N_STATES 129
static const State STATES[N_STATES] = {
  {E_0, 1, NULL, 0, false, 0},
  {NULL, 0, NULL, 0, true, 0},
  {E_2, 1, NULL, 0, false, 1},
  {NULL, 0, NULL, 0, true, 1},
  {E_4, 3, NULL, 0, false, 1},
  {E_5, 1, NULL, 0, false, 1},
  {E_6, 1, NULL, 0, false, 1},
  {E_7, 1, NULL, 0, false, 1},
  {E_8, 1, NULL, 0, false, 1},
  {E_9, 1, NULL, 0, false, 1},
  {E_10, 1, NULL, 0, false, 1},
  {E_11, 1, NULL, 0, false, 1},
  {E_12, 1, NULL, 0, false, 1},
  {E_13, 1, NULL, 0, false, 1},
  {E_14, 1, NULL, 0, false, 1},
  {E_15, 1, NULL, 0, false, 1},
  {E_16, 1, NULL, 0, false, 1},
  {NULL, 0, P_17, 1, false, 2},
  {NULL, 0, NULL, 0, true, 2},
  {E_19, 4, NULL, 0, false, 2},
  {NULL, 0, P_20, 2, false, 2},
  {E_21, 1, NULL, 0, false, 2},
  {E_22, 1, NULL, 0, false, 2},
  {E_23, 1, NULL, 0, false, 2},
  {E_24, 1, NULL, 0, false, 2},
  {NULL, 0, P_25, 1, false, 2},
  {NULL, 0, P_26, 2, false, 3},
  {NULL, 0, NULL, 0, true, 3},
  {E_28, 1, P_28, 1, false, 3},
  {E_29, 4, P_29, 1, false, 3},
  {NULL, 0, P_30, 1, false, 3},
  {E_31, 1, NULL, 0, false, 3},
  {E_32, 1, NULL, 0, false, 3},
  {E_33, 1, NULL, 0, false, 3},
  {E_34, 1, NULL, 0, false, 3},
  {NULL, 0, P_35, 1, false, 3},
  {E_36, 1, NULL, 0, false, 3},
  {E_37, 4, NULL, 0, false, 3},
  {NULL, 0, P_38, 2, false, 3},
  {E_39, 1, NULL, 0, false, 3},
  {E_40, 1, NULL, 0, false, 3},
  {E_41, 1, NULL, 0, false, 3},
  {E_42, 1, NULL, 0, false, 3},
  {NULL, 0, P_43, 1, false, 3},
  {NULL, 0, P_44, 1, false, 4},
  {NULL, 0, NULL, 0, true, 4},
  {NULL, 0, P_46, 1, false, 4},
  {NULL, 0, P_47, 1, false, 4},
  {E_48, 1, P_48, 1, false, 4},
  {NULL, 0, P_49, 1, false, 4},
  {NULL, 0, P_50, 1, false, 4},
  {NULL, 0, P_51, 1, false, 4},
  {NULL, 0, P_52, 1, false, 4},
  {E_53, 1, NULL, 0, false, 4},
  {NULL, 0, P_54, 2, false, 4},
  {E_55, 1, P_55, 1, false, 4},
  {NULL, 0, P_56, 1, false, 4},
  {E_57, 1, NULL, 0, false, 5},
  {NULL, 0, NULL, 0, true, 5},
  {E_59, 1, P_59, 1, false, 5},
  {E_60, 1, NULL, 0, false, 5},
  {NULL, 0, P_61, 1, false, 5},
  {E_62, 1, NULL, 0, false, 5},
  {E_63, 1, P_63, 1, false, 5},
  {NULL, 0, P_64, 1, false, 5},
  {NULL, 0, P_65, 1, false, 5},
  {E_66, 1, NULL, 0, false, 5},
  {E_67, 1, NULL, 0, false, 5},
  {E_68, 1, NULL, 0, false, 5},
  {E_69, 1, P_69, 1, false, 5},
  {E_70, 1, P_70, 1, false, 5},
  {NULL, 0, P_71, 1, false, 5},
  {E_72, 1, NULL, 0, false, 5},
  {E_73, 1, NULL, 0, false, 6},
  {NULL, 0, NULL, 0, true, 6},
  {E_75, 1, P_75, 1, false, 6},
  {E_76, 1, NULL, 0, false, 6},
  {NULL, 0, P_77, 1, false, 6},
  {E_78, 1, NULL, 0, false, 6},
  {E_79, 1, P_79, 1, false, 6},
  {NULL, 0, P_80, 1, false, 6},
  {NULL, 0, P_81, 1, false, 6},
  {E_82, 1, NULL, 0, false, 6},
  {E_83, 1, NULL, 0, false, 6},
  {E_84, 1, NULL, 0, false, 6},
  {E_85, 1, NULL, 0, false, 6},
  {E_86, 1, P_86, 1, false, 6},
  {E_87, 1, P_87, 1, false, 6},
  {NULL, 0, P_88, 1, false, 6},
  {E_89, 1, NULL, 0, false, 6},
  {E_90, 1, NULL, 0, false, 7},
  {NULL, 0, NULL, 0, true, 7},
  {E_92, 1, P_92, 1, false, 7},
  {E_93, 1, NULL, 0, false, 7},
  {NULL, 0, P_94, 1, false, 7},
  {E_95, 1, NULL, 0, false, 7},
  {E_96, 1, P_96, 1, false, 7},
  {NULL, 0, P_97, 1, false, 7},
  {NULL, 0, P_98, 1, false, 7},
  {E_99, 1, NULL, 0, false, 7},
  {E_100, 1, NULL, 0, false, 7},
  {E_101, 1, NULL, 0, false, 7},
  {E_102, 1, NULL, 0, false, 7},
  {E_103, 1, NULL, 0, false, 7},
  {E_104, 1, P_104, 1, false, 7},
  {E_105, 1, P_105, 1, false, 7},
  {NULL, 0, P_106, 1, false, 7},
  {E_107, 1, NULL, 0, false, 7},
  {E_108, 1, P_108, 1, false, 8},
  {NULL, 0, NULL, 0, true, 8},
  {E_110, 1, NULL, 0, false, 8},
  {NULL, 0, P_111, 1, false, 8},
  {NULL, 0, P_112, 2, false, 8},
  {NULL, 0, P_113, 1, false, 8},
  {E_114, 1, P_114, 1, false, 8},
  {E_115, 1, P_115, 1, false, 8},
  {NULL, 0, P_116, 1, false, 8},
  {E_117, 1, NULL, 0, false, 8},
  {E_118, 1, NULL, 0, false, 9},
  {NULL, 0, NULL, 0, true, 9},
  {E_120, 1, P_120, 1, false, 9},
  {E_121, 1, NULL, 0, false, 9},
  {NULL, 0, P_122, 1, false, 9},
  {E_123, 1, P_123, 1, false, 9},
  {NULL, 0, P_124, 1, false, 9},
  {NULL, 0, P_125, 1, false, 9},
  {E_126, 1, NULL, 0, false, 9},
  {NULL, 0, P_127, 2, false, 9},
  {E_128, 1, NULL, 0, false, 9},
};

static bool class_has(int cls, int32_t c) {
  const Class *k = &CLASSES[cls];
  bool in = false;
  for (unsigned i = 0; i < k->n; i++) {
    if (c >= k->ranges[i].lo && c <= k->ranges[i].hi) { in = true; break; }
  }
  // End of input is in a class only when the class names it.
  if (c == EOF_CP) return in && !k->negated;
  return in != k->negated;
}

typedef struct { uint16_t start; enum TokenType sym; uint8_t role; } Owned;
// role: 0 plain, 1 opener (pushes its captured word), 2 closer (pops it).
static const Owned OWNED[] = {
  {0, QUOTE, 0},  // QUOTE
  {2, ESCAPE_SEQUENCE, 0},  // ESCAPE_SEQUENCE
  {17, QCHUNK, 0},  // _QCHUNK
  {26, HCHUNK, 0},  // _HCHUNK
  {44, HEREDOC_END, 2},  // HEREDOC_END
  {57, DIR_ELSE, 0},  // _DIR_ELSE
  {73, DIR_ENDIF, 0},  // _DIR_ENDIF
  {90, DIR_ENDFOR, 0},  // _DIR_ENDFOR
  {108, NL, 0},  // _NL
  {118, HEREDOC_START, 1},  // HEREDOC_START
};
#define N_OWNED 10
#define MAX_TEXT 256
#define MAX_DELIMS 16
#define MAX_WORD 64

typedef struct {
  uint8_t depth;
  uint8_t len[MAX_DELIMS];
  char word[MAX_DELIMS][MAX_WORD];
} Delims;

typedef struct { uint16_t state; int16_t cs, ce; } Thread;
typedef struct { Thread t[N_STATES]; unsigned n; bool seen[N_STATES]; } Threads;

// The delimiter stack is the state; the thread lists are scratch space
// kept here rather than static so that parsers on several threads do not
// share them.
typedef struct {
  Delims delims;
  Threads cur, next, probe;
} Scanner;

static int32_t look(TSLexer *lexer) {
  return lexer->eof(lexer) ? EOF_CP : lexer->lookahead;
}

// Epsilon closure from `s`, with `la` the character that would come next:
// a guarded edge is crossed only when `la` is outside its classes, and a
// tagged edge records the capture's start or end at `pos`.
static void add_thread(Threads *l, uint16_t s, int16_t cs, int16_t ce, int32_t la, int pos) {
  if (l->seen[s]) return;
  l->seen[s] = true;
  l->t[l->n].state = s;
  l->t[l->n].cs = cs;
  l->t[l->n].ce = ce;
  l->n++;
  const State *st = &STATES[s];
  for (unsigned i = 0; i < st->n_eps; i++) {
    const Eps *e = &st->eps[i];
    bool blocked = false;
    for (unsigned g = 0; g < e->n_guard; g++) {
      if (class_has(e->guard[g], la)) { blocked = true; break; }
    }
    if (blocked) continue;
    add_thread(l, e->target, e->tag == 1 ? (int16_t)pos : cs, e->tag == 2 ? (int16_t)pos : ce, la, pos);
  }
}

static bool can_start(Threads *l, const bool *cand, int32_t la) {
  memset(l, 0, sizeof(*l));
  for (unsigned i = 0; i < N_OWNED; i++) {
    if (cand[i]) add_thread(l, OWNED[i].start, -1, -1, la, 0);
  }
  for (unsigned k = 0; k < l->n; k++) {
    const State *st = &STATES[l->t[k].state];
    for (unsigned e = 0; e < st->n_edges; e++) {
      if (class_has(st->edges[e].cls, la)) return true;
    }
  }
  return false;
}

static bool word_on_top(const Scanner *s, const char *text, int cs, int ce) {
  if (s->delims.depth == 0 || cs < 0 || ce < cs) return false;
  const Delims *d = &s->delims;
  unsigned n = d->depth - 1;
  if ((int)d->len[n] != ce - cs) return false;
  return memcmp(d->word[n], text + cs, (size_t)(ce - cs)) == 0;
}

// Every valid owned token at once: the live states of all of them are
// stepped together, the token ends at the last position where one was
// accepting, and among several the closer wins outright and otherwise the
// longest, ties to the first declared. `mark_end` at each accept is what
// makes this longest-match with a lexer that cannot step back.
static bool scan_owned(Scanner *s, TSLexer *lexer, const bool *valid) {
  Threads *cur = &s->cur;
  Threads *next = &s->next;
  bool cand[N_OWNED];
  unsigned n_cand = 0;
  for (unsigned i = 0; i < N_OWNED; i++) {
    cand[i] = valid[OWNED[i].sym] && (OWNED[i].role != 2 || s->delims.depth > 0);
    if (cand[i]) n_cand++;
  }
  if (n_cand == 0) return false;

  // Layout no candidate could begin with is skipped; the rest is theirs.
  for (;;) {
    int32_t la = look(lexer);
    if (la == EOF_CP || !is_layout(la) || can_start(&s->probe, cand, la)) break;
    lexer->advance(lexer, true);
  }
  // A closer is matched at the start of a line only.
  bool at_line_start = lexer->get_column(lexer) == 0;
  for (unsigned i = 0; i < N_OWNED; i++) {
    if (cand[i] && OWNED[i].role == 2 && !at_line_start) cand[i] = false;
  }

  char text[MAX_TEXT];
  int pos = 0;
  int best = -1, best_len = -1;
  int16_t best_cs = -1, best_ce = -1;
  int32_t la = look(lexer);
  memset(cur, 0, sizeof(*cur));
  for (unsigned i = 0; i < N_OWNED; i++) {
    if (cand[i]) add_thread(cur, OWNED[i].start, -1, -1, la, 0);
  }
  for (;;) {
    bool decided = false;
    for (unsigned k = 0; k < cur->n && !decided; k++) {
      const Thread *t = &cur->t[k];
      const State *st = &STATES[t->state];
      if (!st->accept) continue;
      int tok = st->tok;
      if (OWNED[tok].role == 2) {
        if (word_on_top(s, text, t->cs, t->ce)) {
          best = tok;
          best_len = pos;
          lexer->mark_end(lexer);
          decided = true;
        }
        continue;
      }
      if (best < 0 || pos > best_len || (pos == best_len && tok < best)) {
        best = tok;
        best_len = pos;
        best_cs = t->cs;
        best_ce = t->ce;
        lexer->mark_end(lexer);
      }
    }
    if (decided || la == EOF_CP) break;
    // Step every live state over `la`; the closure waits for the next
    // lookahead, which the guards need.
    memset(next, 0, sizeof(*next));
    unsigned np = 0;
    for (unsigned k = 0; k < cur->n; k++) {
      const State *st = &STATES[cur->t[k].state];
      for (unsigned e = 0; e < st->n_edges; e++) {
        if (!class_has(st->edges[e].cls, la)) continue;
        uint16_t target = st->edges[e].target;
        if (next->seen[target]) continue;
        next->seen[target] = true;
        next->t[np].state = target;
        next->t[np].cs = cur->t[k].cs;
        next->t[np].ce = cur->t[k].ce;
        np++;
      }
    }
    if (np == 0) break;
    if (pos < MAX_TEXT) text[pos] = (char)la;
    pos++;
    lexer->advance(lexer, false);
    la = look(lexer);
    memset(cur, 0, sizeof(*cur));
    for (unsigned k = 0; k < np; k++) {
      add_thread(cur, next->t[k].state, next->t[k].cs, next->t[k].ce, la, pos);
    }
  }
  if (best < 0) return false;
  if (OWNED[best].role == 1) {
    if (best_cs < 0 || best_ce < best_cs || s->delims.depth >= MAX_DELIMS || best_ce - best_cs > MAX_WORD) return false;
    Delims *d = &s->delims;
    d->len[d->depth] = (uint8_t)(best_ce - best_cs);
    memcpy(d->word[d->depth], text + best_cs, (size_t)(best_ce - best_cs));
    d->depth++;
  } else if (OWNED[best].role == 2) {
    s->delims.depth--;
  }
  lexer->result_symbol = OWNED[best].sym;
  return true;
}

void *tree_sitter_hcl_external_scanner_create(void) { return calloc(1, sizeof(Scanner)); }
void tree_sitter_hcl_external_scanner_destroy(void *payload) { free(payload); }
unsigned tree_sitter_hcl_external_scanner_serialize(void *payload, char *buffer) {
  Scanner *s = payload;
  unsigned n = 0;
  buffer[n++] = (char)s->delims.depth;
  for (unsigned i = 0; i < s->delims.depth; i++) {
    buffer[n++] = (char)s->delims.len[i];
    memcpy(buffer + n, s->delims.word[i], s->delims.len[i]);
    n += s->delims.len[i];
  }
  return n;
}
void tree_sitter_hcl_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  Scanner *s = payload;
  memset(s, 0, sizeof(Scanner));
  if (length == 0) return;
  unsigned n = 0;
  uint8_t depth = (uint8_t)buffer[n++];
  for (unsigned i = 0; i < depth && n < length && i < MAX_DELIMS; i++) {
    s->delims.len[i] = (uint8_t)buffer[n++];
    memcpy(s->delims.word[i], buffer + n, s->delims.len[i]);
    n += s->delims.len[i];
    s->delims.depth++;
  }
}

bool tree_sitter_hcl_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid) {
  (void)payload;
  // During error recovery every symbol is marked valid (the sentinel is
  // never produced, so seeing it valid is the tell).
  bool recovery = valid[ERROR_SENTINEL];

  // The scanner-owned lexical sorts, at the raw position: what they may
  // begin with is theirs, and layout is skipped only where none of them
  // could start. Nothing is offered during recovery, so the delimiter
  // stack stays in step with a parse that is happening.
  if (recovery) return false;
  if (scan_owned((Scanner *)payload, lexer, valid)) return true;
  return false;
}
