//! The vocabulary lowering: the committed `roles.json` of each spike that
//! declares a `vocabulary` section is what the lowering produces, the
//! vocabulary's terms are real supertypes of the lowered grammar, and the
//! tree is untouched by the threading.

use std::path::{Path, PathBuf};

fn spike(name: &str) -> PathBuf {
    Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/spike")).join(name)
}

fn everything(name: &str) -> treebank_sdf3::Everything {
    let module = treebank_sdf3::load_module(&spike(name).join(format!("{name}.sdf3"))).unwrap();
    treebank_sdf3::lower_all(&module).unwrap()
}

#[test]
fn roles_json_is_what_the_lowering_produces() {
    for name in ["pyish", "rustish", "jsish"] {
        let e = everything(name);
        let v = e.vocab.expect("declares a vocabulary");
        let produced = serde_json::to_string_pretty(&v.roles).unwrap() + "\n";
        let committed = std::fs::read_to_string(spike(name).join("roles.json")).unwrap();
        assert_eq!(produced, committed, "spike/{name}/roles.json is stale; regenerate it");
        let produced = serde_json::to_string_pretty(&e.lowered.grammar).unwrap() + "\n";
        let committed = std::fs::read_to_string(spike(name).join("grammar.json")).unwrap();
        // rustish's committed grammar also carries its pinned conflict.
        if name != "rustish" {
            assert_eq!(produced, committed, "spike/{name}/grammar.json is stale; regenerate it");
        }
    }
}

#[test]
fn a_whole_sort_term_renames_and_a_constructor_term_threads() {
    let e = everything("pyish");
    let g = &e.lowered.grammar;
    let sup: Vec<&str> = g["supertypes"].as_array().unwrap().iter().map(|v| v.as_str().unwrap()).collect();
    // `_statement = Stmt`: the sort's own supertype, renamed; `_stmt` is gone.
    assert!(sup.contains(&"_statement") && !sup.contains(&"_stmt"), "{sup:?}");
    assert!(g["rules"].get("_stmt").is_none());
    // `_branch = Stmt.If`: a new supertype over `if`, and `_statement` now
    // reaches `if` through `_control_flow` and `_branch`, not directly.
    let branch = serde_json::to_string(&g["rules"]["_branch"]).unwrap();
    assert!(branch.contains(r#"{"type":"SYMBOL","name":"if"}"#), "{branch}");
    let stmt = serde_json::to_string(&g["rules"]["_statement"]).unwrap();
    assert!(stmt.contains("_control_flow") && !stmt.contains(r#""name":"if""#), "{stmt}");
    // `_body = Block`: every field that held `block` holds `_body`.
    let if_rule = serde_json::to_string(&g["rules"]["if"]).unwrap();
    assert!(if_rule.contains(r#""name":"_body""#) && !if_rule.contains(r#""name":"block""#), "{if_rule}");
    // Names followed the rename, so the ANTLR backend and bindings agree.
    assert_eq!(e.lowered.names.sort_rule["Stmt"], "_statement");
    // Facets: two derived from bindings, one from LAYOUT, one declared.
    let roles = e.vocab.unwrap().roles;
    for f in ["_scope", "_binding", "_callable", "_comment", "_clause"] {
        assert!(roles["facets"].get(f).is_some(), "missing facet {f}: {}", roles["facets"]);
    }
    assert_eq!(roles["facets"]["_callable"], serde_json::json!(["def"]));
}

#[test]
fn the_real_checker_accepts_every_spike_manifest() {
    // node-types.json is generated by verify.sh; when it is present, hold
    // the manifest to treebank::check exactly as CI holds the grammars.
    for name in ["pyish", "rustish", "jsish"] {
        let nt_path = spike(name).join("src/node-types.json");
        if !nt_path.exists() {
            continue;
        }
        let nt = treebank::node_types::NodeTypes::load(&nt_path).unwrap();
        let roles = treebank::roles::RolesManifest::load(&spike(name).join("roles.json")).unwrap();
        let findings = treebank::check::check(&nt, &roles, treebank::vocabulary());
        assert!(findings.is_empty(), "{name}: {findings:?}");
    }
}
