; GENERATED by treebank-sdf3 from the scope/binds/refers attributes of
; pyish.sdf3, in treebank's locals vocabulary. bindings.json is the exact
; data; this is the query-dialect view of it.

; --- where names live
[(program) (def)] @local.scope

; --- what introduces a name
(assign target: (id) @local.definition.var)

; bindings.json: scope = module. The dialect has no way to say it.
(global names: (id) @local.definition.var)

(def name: (id) @local.definition.function
  (#set! definition.function.scope "parent"))

(param name: (id) @local.definition.parameter)

; --- what mentions a name
(id) @local.reference
