; GENERATED by `treebank queries --write` from queries/highlights.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; java's own node types. Edit queries/highlights.scm and regenerate, or the next
; --check will fail.

; --- the leaves a reader looks at first -----------------------------------

[(block_comment) (line_comment)] @comment
[(character_literal) (string_literal) (text_block)] @string
(_literal) @number

; --- names ----------------------------------------------------------------
;
; `_identifier` is every name-shaped token, so it is the fallback that later
; patterns narrow.

[(identifier) (scoped_identifier) (scoped_type_identifier) (type_identifier)] @variable

; --- things that are called ------------------------------------------------
;
; Guarded, because not every language treebank parses computes. YAML has no
; callable and no invocation, and a pattern naming a term its grammar does
; not declare is a QueryError at load time rather than a zero-match, so the
; block is dropped for the grammars that lack the term instead of the file
; failing to compile for them.

[(annotation_type_element) (compact_constructor_declaration) (constructor_declaration) (lambda) (method_declaration) (method_reference)] @function

(_invocation) @function.call

; --- control flow ----------------------------------------------------------
;
; These capture the whole construct rather than its keyword: the keyword is
; an anonymous token, and an anonymous token has no vocabulary term. A
; per-grammar supplement is where `if` and `while` themselves get coloured.
;
; Guarded for the same reason as the block above: a data language alters no
; sequential execution because it has none.

(_loop) @keyword.repeat

(_branch) @keyword.conditional

(_jump) @keyword.return

(_directive) @keyword.import
