// GENERATED by treebank-sdf3 from the module's layout constraints. Do not
// edit: the lowering regenerates it. See src/scanner.rs for the rules.

#include "tree_sitter/parser.h"
#include <stdbool.h>

enum TokenType {
  REGEX,
  MINUS_SPACED_TIGHT,
  STAR_SPACED_TIGHT,
  LBRACKET_ADJACENT,
  LBRACKET_SPACED,
  LPAREN_ADJACENT,
  LPAREN_SPACED,
  MINUS,
  SLASH,
  STAR,
  ERROR_SENTINEL,
};

typedef struct {
  int32_t ch;
  bool before_req, before_forbid, after_req, after_forbid;
  int32_t closer;
  enum TokenType sym;
} Variant;

// Most specific first; the default for a spelling is last.
static const Variant VARIANTS[] = {
  {'/', true, false, false, true, '/', REGEX},
  {'-', true, false, false, true, 0, MINUS_SPACED_TIGHT},
  {'*', true, false, false, true, 0, STAR_SPACED_TIGHT},
  {'[', false, true, false, false, 0, LBRACKET_ADJACENT},
  {'[', true, false, false, false, 0, LBRACKET_SPACED},
  {'(', false, true, false, false, 0, LPAREN_ADJACENT},
  {'(', true, false, false, false, 0, LPAREN_SPACED},
  {'-', false, false, false, false, 0, MINUS},
  {'/', false, false, false, false, 0, SLASH},
  {'*', false, false, false, false, 0, STAR},
};
static const unsigned VARIANT_COUNT = sizeof(VARIANTS) / sizeof(VARIANTS[0]);

static bool is_layout(int32_t c) {
  return c == ' ' || c == '\t';
}

static bool ends_token(int32_t c) {
  return c == 0 || c == '\n' || c == '\r' || is_layout(c);
}

void *tree_sitter_rubyish_external_scanner_create(void) { return NULL; }
void tree_sitter_rubyish_external_scanner_destroy(void *payload) { (void)payload; }
unsigned tree_sitter_rubyish_external_scanner_serialize(void *payload, char *buffer) { (void)payload; (void)buffer; return 0; }
void tree_sitter_rubyish_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) { (void)payload; (void)buffer; (void)length; }

bool tree_sitter_rubyish_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid) {
  (void)payload;
  // During error recovery every symbol is marked valid (the sentinel is
  // never produced, so seeing it valid is the tell). Decide by spacing then.
  bool recovery = valid[ERROR_SENTINEL];

  bool space_before = false;
  while (is_layout(lexer->lookahead)) {
    lexer->advance(lexer, true);
    space_before = true;
  }
  int32_t c = lexer->lookahead;

  unsigned n_valid = 0;
  for (unsigned i = 0; i < VARIANT_COUNT; i++) {
    if (VARIANTS[i].ch == c && (recovery || valid[VARIANTS[i].sym])) n_valid++;
  }
  if (n_valid == 0) return false;

  lexer->advance(lexer, false);
  lexer->mark_end(lexer);
  bool space_after = ends_token(lexer->lookahead);

  for (unsigned i = 0; i < VARIANT_COUNT; i++) {
    const Variant *v = &VARIANTS[i];
    if (v->ch != c || !(recovery || valid[v->sym])) continue;
    // With one candidate the parser has already decided; spacing only
    // arbitrates between several.
    bool ok = n_valid == 1
      || ((!v->before_req || space_before) && (!v->before_forbid || !space_before)
          && (!v->after_req || space_after) && (!v->after_forbid || !space_after));
    if (!ok) continue;
    if (v->closer) {
      // A lexical sort scanned whole: consume to the closer on this line.
      // If it does not close, fall through to the next candidate with the
      // token still ending at the opener.
      while (lexer->lookahead != v->closer && lexer->lookahead != '\n' && lexer->lookahead != 0) {
        lexer->advance(lexer, false);
      }
      if (lexer->lookahead != v->closer) continue;
      lexer->advance(lexer, false);
      lexer->mark_end(lexer);
    }
    lexer->result_symbol = v->sym;
    return true;
  }
  return false;
}
