//! Consumer smoke test for the published grammar crates.
//!
//! This is deliberately an *outside* view. It depends on the crates the way a
//! real user would — by their published names, resolved from a registry, under
//! upstream's names via cargo's `package = ` rename — and then parses code with
//! them. Passing proves three things the publishing pipeline cannot prove about
//! itself:
//!
//!   1. the tarball we uploaded resolves, builds and links as a dependency;
//!   2. the `[lib] name` pin really does make these drop-in, so
//!      `use tree_sitter_rust::LANGUAGE` compiles against `treebank-grammar-rust`;
//!   3. what a consumer gets is the *patched* grammar — every fixture is a
//!      construct upstream rejects (or, for `must-reject`, wrongly accepts).
//!
//! Its Cargo.toml and its case list are generated by scripts/test-publish.sh
//! from grammars.json, because both the versions and the set of grammars under
//! test are only known at test time — a change to one grammar tests that
//! grammar alone.
use tree_sitter::{Language, Parser};

/// What the parse of a fixture must look like.
#[derive(Clone, Copy, PartialEq)]
enum Expect {
    /// Valid code upstream rejects: our grammar must accept it cleanly.
    Clean,
    /// Invalid code upstream accepts: our grammar must still reject it.
    Error,
}

fn check(label: &str, language: Language, source: &str, expect: Expect) -> bool {
    let mut parser = Parser::new();
    if let Err(e) = parser.set_language(&language) {
        println!("  FAIL {label}: could not load language: {e}");
        return false;
    }
    let Some(tree) = parser.parse(source, None) else {
        println!("  FAIL {label}: parser returned no tree");
        return false;
    };
    let root = tree.root_node();
    // has_error() covers both ERROR and MISSING nodes.
    let errored = root.has_error();
    let ok = match expect {
        Expect::Clean => !errored,
        Expect::Error => errored,
    };
    if ok {
        let what = if expect == Expect::Clean { "parsed clean" } else { "rejected, as it must be" };
        println!("  ok   {label}: {what}");
    } else {
        match expect {
            Expect::Clean => {
                println!("  FAIL {label}: expected a clean parse, got an error node.");
                println!("       This is what an *unpatched* upstream grammar does.");
                if let Some(n) = first_error(root) {
                    println!("       first error at line {}: {:?}", n.start_position().row + 1, n.kind());
                }
            }
            Expect::Error => {
                println!("  FAIL {label}: parsed clean, but this input is invalid and must be rejected.");
                println!("       This is what an *unpatched* upstream grammar does.");
            }
        }
    }
    ok
}

fn first_error(node: tree_sitter::Node) -> Option<tree_sitter::Node> {
    if node.is_error() || node.is_missing() {
        return Some(node);
    }
    let mut cursor = node.walk();
    let found = node.children(&mut cursor).find_map(first_error);
    found
}

// Generated by scripts/test-publish.sh from grammars.json. Not committed: it
// names only the grammars this run is testing.
include!("cases.rs");

fn main() {
    let cases = cases();
    println!("consumer test: {} fixtures", cases.len());
    let failed = cases
        .into_iter()
        .filter(|(label, language, source, expect)| !check(label, language.clone(), source, *expect))
        .count();

    if failed == 0 {
        println!("consumer test: all fixtures behaved as the patch series says they should");
    } else {
        eprintln!("consumer test: {failed} fixture(s) failed");
        std::process::exit(1);
    }
}
