; GENERATED by `treebank queries --write` from queries/highlights.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; cpp's own node types. Edit queries/highlights.scm and regenerate, or the next
; --check will fail.

; --- the leaves a reader looks at first -----------------------------------

[(comment)] @comment
[(concatenated_string) (raw_string_literal) (string_literal) (system_lib_string)] @string
(_literal) @number

; --- names ----------------------------------------------------------------
;
; `_identifier` is every name-shaped token, so it is the fallback that later
; patterns narrow.

[(destructor_name) (identifier) (nested_namespace_specifier) (operator_name) (qualified_identifier) (type_identifier)] @variable

; --- things that are called ------------------------------------------------

[(function_declarator) (function_definition) (lambda_expression) (operator_name) (preproc_function_def)] @function
(_invocation) @function.call

; --- control flow ----------------------------------------------------------
;
; These capture the whole construct rather than its keyword: the keyword is
; an anonymous token, and an anonymous token has no vocabulary term. A
; per-grammar supplement is where `if` and `while` themselves get coloured.

(_loop) @keyword.repeat
(_branch) @keyword.conditional
(_jump) @keyword.return
(_directive) @keyword.import
