; GENERATED by `treebank queries` from queries/locals.scm -- do not edit.
;
; The source names vocabulary terms; the nominal ones below have been
; expanded into cpp's own node types. Edit queries/locals.scm and
; regenerate, or the next --check will fail.

; --- where names live ------------------------------------------------------
;
; A scope is anything that can contain a binding without leaking it. What
; counts differs per language -- a block, a function body, a module, a `do`
; end -- and each grammar declares its own members.

[(catch_clause) (class_specifier) (compound_statement) (declaration_list) (field_declaration_list) (for_statement) (function_definition) (lambda_expression) (namespace_definition) (requirement_seq) (translation_unit)] @local.scope

; --- what introduces a name ------------------------------------------------
;
; The capture goes on the NAME, not on the construct: an editor renames the
; identifier, and needs the range of the thing it would rewrite. Members that
; have no `name` field are dropped when this is expanded, which is why a
; language whose bindings are positional loses those patterns rather than
; producing a pattern that cannot match.

[(preproc_function_def name: (_) @local.definition.function)]

[(alias_declaration name: (_) @local.definition.var) (enumerator name: (_) @local.definition.var) (field_initializer name: (_) @local.definition.var) (namespace_alias_definition name: (_) @local.definition.var) (namespace_definition name: (_) @local.definition.var) (preproc_def name: (_) @local.definition.var) (preproc_function_def name: (_) @local.definition.var) (type_parameter_declaration name: (_) @local.definition.var) (using_declaration name: (_) @local.definition.var) (variadic_type_parameter_declaration name: (_) @local.definition.var)]

; A parameter is a definition, and the one place a caller's name meets the
; callee's. bash has no term for it: a bash function takes `$1`, not a named
; parameter, so this is omitted there rather than dropped from everyone.
[(type_parameter_declaration name: (_) @local.definition.parameter) (variadic_type_parameter_declaration name: (_) @local.definition.parameter)]

; --- what mentions a name --------------------------------------------------
;
; Every name-shaped token is a reference until something more specific claims
; it. The locals engine resolves each against the definitions in scope, so
; over-capturing here is cheap and under-capturing is not.

[(destructor_name) (identifier) (nested_namespace_specifier) (operator_name) (qualified_identifier) (type_identifier)] @local.reference
