; GENERATED by `treebank queries --write` from queries/locals.scm -- do not edit.
;
; The source names vocabulary terms; the facets below have been expanded into
; rust's own node types. Edit queries/locals.scm and regenerate, or the next
; --check will fail.
;
; Omitted: rust has _parameter, but no member of it takes
; the field the pattern asks for.

; --- where names live ------------------------------------------------------
;
; A scope is anything that can contain a binding without leaking it. What
; counts differs per language -- a block, a function body, a module, a `do`
; end -- and each grammar declares its own members.

[(source_file) (function_definition) (block) (closure_expression) (module_definition) (impl_block) (trait_definition) (async_block) (const_block) (unsafe_block) (match_arm) (loop_expression) (while_expression) (for_expression)] @local.scope

; --- what introduces a name ------------------------------------------------
;
; The capture goes on the NAME, not on the construct: an editor renames the
; identifier, and needs the range of the thing it would rewrite. Members that
; have no `name` field are dropped when this is expanded, which is why a
; language whose bindings are positional loses those patterns rather than
; producing a pattern that cannot match.

[(function_definition name: (_) @local.definition.function)]

[(function_definition name: (_) @local.definition.var) (struct_definition name: (_) @local.definition.var) (enum_definition name: (_) @local.definition.var) (union_definition name: (_) @local.definition.var) (trait_definition name: (_) @local.definition.var) (module_definition name: (_) @local.definition.var) (module_declaration name: (_) @local.definition.var) (const_definition name: (_) @local.definition.var) (static_definition name: (_) @local.definition.var) (type_alias name: (_) @local.definition.var) (macro_definition name: (_) @local.definition.var) (extern_crate_declaration name: (_) @local.definition.var) (type_parameter name: (_) @local.definition.var) (const_parameter name: (_) @local.definition.var) (field_declaration name: (_) @local.definition.var) (enum_variant name: (_) @local.definition.var) (capture_pattern name: (_) @local.definition.var) (field_pattern name: (_) @local.definition.var)]

; --- what mentions a name --------------------------------------------------
;
; Every name-shaped token is a reference until something more specific claims
; it. The locals engine resolves each against the definitions in scope, so
; over-capturing here is cheap and under-capturing is not.

[(identifier) (lifetime) (scoped_identifier) (type_identifier)] @local.reference
